import { parse, printSchema, GraphQLSchema } from "graphql";
import { codegen } from "@graphql-codegen/core";
import { plugin as typescriptPlugin } from "@graphql-codegen/typescript";
import { plugin as typescriptOperationsPlugin } from "@graphql-codegen/typescript-operations";

export const generateTypes = async (schema: GraphQLSchema) => {
  try {
    const res = await codegen({
      filename: process.cwd() + "/.forestry/autoschema.gql",
      schema: parse(printSchema(schema)),
      documents: [],
      config: {},
      plugins: [
        // { forestryOperations: {} },
        { typescript: {} },
        { typescriptOperations: {} },
      ],
      pluginMap: {
        // NOTE: we may not need to generate types for the query since
        // it's auto-generated by us
        // forestryOperations: {
        //   plugin: (schema, documents, config) => {
        //     documents.push({
        //       document: queryBuilder(schema),
        //     });
        //     return undefined;
        //   },
        // },
        typescript: {
          plugin: typescriptPlugin,
        },
        typescriptOperations: {
          plugin: typescriptOperationsPlugin,
        },
      },
    });
    return res;
  } catch (e) {
    console.error(e);
  }
};
