---
sections:
  - type: directory
    path: content/posts
    label: Posts
    create: documents
    match: "**/*.md"
    templates:
      - post
  - type: directory
    path: content/authors
    label: Authors
    create: documents
    match: "**/*.md"
    templates:
      - author
