initFields:
  version: 0.1.0
  dependencies:
    "@forestryio/build": "workspace:packages/build"
  bin:
    "forestry:start": bin.js
  files: dist/*
  main: dist/index.js
  name: ""
  scripts:
    build: forestry-build
    graphiql: next dev -p 3001
    watch: forestry-watch
  typings: dist/types.d.ts

initScope: forestryio

npmScopes:
  forestryio:
    npmAlwaysAuth: false
    npmAuthIdent: "${FORESTRYIO_NPM_AUTH_IDENT:-must_supply_this_value_in_zshrc}"
    npmAuthToken: "${FORESTRYIO_NPM_AUTH_TOKEN:-must_supply_this_value_in_zshrc}"
    npmPublishRegistry: "https://registry.npmjs.org"
    npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@tailwindcss/typography@*":
    dependencies:
      "lodash": ^4.17.20
  "@graphql-codegen/cli@*":
    dependencies:
      apollo-link: ^1.2.14
      apollo-link-http-common: ^0.2.16
      apollo-upload-client: ^13.0.0
      graphql: ^14.6.0
      graphql-tools: ^5.0.0
  "@graphql-codegen/plugin-helpers@*":
    dependencies:
      graphql: ^14.6.0
  express-graphql@*:
    dependencies:
      graphql: ^14.6.0
  graphiql-code-exporter@*:
    dependencies:
      codemirror: ^5.55.0
  graphiql@*:
    dependencies:
      prop-types: ^15.7.2
  "@snowpack/app-scripts-react@*":
    dependencies:
      react-refresh: ^0.8.3
  tsup@*:
    dependencies:
      typescript: ^4.0.3
  next@*:
    dependencies:
      chalk: ^4.0.0
      schema-utils: ^2.6.6
  # Start of tina-related fixes
  "@tinacms/icons@*":
    peerDependencies:
      react: ^16.13.0
  "@tinacms/styles@*":
    peerDependencies:
      react: ^16.13.0
  "react-dismissible@*":
    peerDependencies:
      react: ^16.13.0
  "react-color@*": # https://github.com/casesandberg/react-color/pull/658
    peerDependencies:
      react: ^16.13.0
  "reactcss@*": # Same author, no PR yet - https://github.com/casesandberg/reactcss/issues?q=peerDependencies
    peerDependencies:
      react: ^16.13.0
  "react-beautiful-dnd@*":
    peerDependencies:
      react-dom: ^16.13.0
  "@tinacms/fields@*":
    peerDependencies:
      react: ^16.13.0
      "prop-types": ">=15"
      "@tinacms/form-builder": "latest"
      "@tinacms/icons": "latest"
      "@tinacms/react-core": "latest"
      "@tinacms/react-forms": "latest"
      "@tinacms/styles": "latest"
      "react-beautiful-dnd": "^11.0.5" #
  "@tinacms/react-sidebar@*":
    peerDependencies:
      "prop-types": ">=15"
  "@tinacms/react-toolbar@*": # this is listed property for this package
    peerDependencies:
      react-dom: ^16.13.0
      "react-beautiful-dnd": "^11.0.5"
  "@tinacms/react-forms@*":
    peerDependencies:
      "prop-types": ">=15"
      "final-form": "^4.18.2" # https://github.com/tinacms/tinacms/blob/859b8db0eb7cc63825e51bff0a1d024e5398135c/packages/@tinacms/forms/package.json#L35
  "@tinacms/form-builder@*":
    peerDependencies:
      "final-form": "^4.18.2"
  tinacms@*:
    dependencies:
      "react-beautiful-dnd": "^11.0.5"
      "prop-types": ">=15"
      "final-form": "^4.18.2" # https://github.com/tinacms/tinacms/blob/859b8db0eb7cc63825e51bff0a1d024e5398135c/packages/@tinacms/forms/package.json#L35

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-2.1.1.cjs
