yarnPath: ".yarn/releases/yarn-berry.js"
packageExtensions:
  next@*:
    dependencies:
      schema-utils: ^2.6.6
      chalk: ^4.0.0
  "@graphql-codegen/cli@*":
    dependencies:
      apollo-link: ^1.2.14
      apollo-link-http-common: ^0.2.16
      apollo-upload-client: ^13.0.0
      apollo-utilities@*: null
      graphql: ^14.6.0
      graphql-tools: ^5.0.0
  "graphiql@*":
    dependencies:
      prop-types: ^15.7.2
  "graphiql-code-exporter@*":
    dependencies:
      codemirror: ^5.55.0
  "@graphql-codegen/plugin-helpers@*":
    dependencies:
      graphql: ^14.6.0
  "@icons/material@*":
    dependencies:
      react: ^16.13.0
  "tinacms@*":
    dependencies:
      "@tinacms/fields": 0.11.0
      "@tinacms/forms": 0.4.2
  "@tinacms/fields@*":
    dependencies:
      "@tinacms/form-builder": 0.3.3
      "@tinacms/icons": next
      "@tinacms/react-core": 0.2.12
      "@tinacms/react-forms": 0.1.6
      "@tinacms/styles": next
      "react-beautiful-dnd": "*"
      react-dom: ^16.13.0 # Note this was a guess, the error shows up for @tinacms/react-forms
  "@tinacms/form-builder@*":
    dependencies:
      "prop-types": "*"
  "@tinacms/styles@*":
    dependencies:
      react: ^16.13.0
  "@tinacms/icons@*":
    dependencies:
      react: ^16.13.0
  "@tinacms/react-forms@*":
    dependencies:
      "@tinacms/react-modals": next
      react-dom: ^16.13.0
  create-react-class@*:
    dependencies:
      react: ^16.13.0
  express-graphql@*:
    dependencies:
      graphql: ^14.6.0
  react-color@*:
    dependencies:
      react: ^16.13.0
  react-dismissible@*:
    dependencies:
      react: ^16.13.0
  react-final-form@*:
    dependencies:
      final-form: "*"
  react-redux@*:
    dependencies:
      react-dom: ^16.13.0
  reactcss@*:
    dependencies:
      react: ^16.13.0
  styled-components@*:
    dependencies:
      react-is: "*"
  tsdx@*:
    dependencies:
      semver: ^7.1.3

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "@yarnpkg/plugin-interactive-tools"
