---
label: Article
name: article
fields:
  - type: text
    label: Title
    name: title
  - name: hero
    type: file
    label: Hero
  - name: author
    label: Author
    type: select
    config:
      source:
        type: pages
        section: authors
