// DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
export type Maybe<T> = T | null;
export type Exact<T extends { [key: string]: any }> = { [K in keyof T]: T[K] };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  /** References another document, used as a foreign key */
  Reference: any;
  JSON: any;
  JSONObject: any;
};

export type Node = {
  id: Scalars['ID'];
};

export type Document = {
  sys?: Maybe<SystemInfo>;
  id: Scalars['ID'];
};

export type FormField = {
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
};




export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename?: Maybe<Scalars['String']>;
  basename?: Maybe<Scalars['String']>;
  breadcrumbs?: Maybe<Array<Maybe<Scalars['String']>>>;
  path?: Maybe<Scalars['String']>;
  relativePath?: Maybe<Scalars['String']>;
  extension?: Maybe<Scalars['String']>;
  template?: Maybe<Scalars['String']>;
  section?: Maybe<Section>;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: Maybe<Scalars['Boolean']>;
};

export type Section = {
  __typename?: 'Section';
  type?: Maybe<Scalars['String']>;
  path?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  create?: Maybe<Scalars['String']>;
  match?: Maybe<Scalars['String']>;
  new_doc_ext?: Maybe<Scalars['String']>;
  templates?: Maybe<Array<Maybe<Scalars['String']>>>;
  slug?: Maybe<Scalars['String']>;
  documents?: Maybe<Array<Maybe<Document>>>;
};

export type SectionDocumentUnion = Posts_Document;

export type SectionParams = {
  posts?: Maybe<Posts_Input>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument?: Maybe<Document>;
  updateDocument?: Maybe<SectionDocumentUnion>;
  updatePostsDocument?: Maybe<Posts_Document>;
};


export type MutationAddPendingDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
  section?: Maybe<Scalars['String']>;
  template?: Maybe<Scalars['String']>;
};


export type MutationUpdateDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
  params?: Maybe<SectionParams>;
};


export type MutationUpdatePostsDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
  params?: Maybe<Posts_Input>;
};

export type Query = {
  __typename?: 'Query';
  _queryString?: Maybe<Scalars['String']>;
  node?: Maybe<Node>;
  getDocument?: Maybe<SectionDocumentUnion>;
  getSections?: Maybe<Array<Maybe<Section>>>;
  getSection?: Maybe<Section>;
  getPostsDocument?: Maybe<Posts_Document>;
  getPostsList?: Maybe<Array<Maybe<Posts_Document>>>;
};


export type QueryNodeArgs = {
  id: Scalars['ID'];
};


export type QueryGetDocumentArgs = {
  section?: Maybe<Scalars['String']>;
  relativePath?: Maybe<Scalars['String']>;
};


export type QueryGetSectionArgs = {
  section?: Maybe<Scalars['String']>;
};


export type QueryGetPostsDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
};

export type Posts_Data = Post4_Doc_Data | Post3_Doc_Data;

export type Posts_Input = {
  post4?: Maybe<Post4_Doc_Input>;
  post3?: Maybe<Post3_Doc_Input>;
};

export type Posts_Values = Post4_Doc_Values | Post3_Doc_Values;

export type Posts_Form = Post4_Doc_Form | Post3_Doc_Form;

export type Posts_Document = Node & Document & {
  __typename?: 'Posts_Document';
  id: Scalars['ID'];
  sys?: Maybe<SystemInfo>;
  data?: Maybe<Posts_Data>;
  values?: Maybe<Posts_Values>;
  form?: Maybe<Posts_Form>;
};

export type LongTextValue = {
  __typename?: 'LongTextValue';
  raw?: Maybe<Scalars['String']>;
  markdownAst?: Maybe<Scalars['JSONObject']>;
  html?: Maybe<Scalars['String']>;
};

export type Post4_Doc_Data = {
  __typename?: 'Post4_Doc_Data';
  titlez?: Maybe<Scalars['String']>;
  author?: Maybe<Posts_Document>;
  _body?: Maybe<LongTextValue>;
};

export type LongTextInitialValue = {
  __typename?: 'LongTextInitialValue';
  raw?: Maybe<Scalars['String']>;
};

export type Post4_Doc_Values = {
  __typename?: 'Post4_Doc_Values';
  titlez?: Maybe<Scalars['String']>;
  author?: Maybe<Scalars['Reference']>;
  _body?: Maybe<LongTextInitialValue>;
  _template?: Maybe<Scalars['String']>;
};

export type TextField = FormField & {
  __typename?: 'TextField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
};

export type SelectField = FormField & {
  __typename?: 'SelectField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  options?: Maybe<Array<Maybe<Scalars['String']>>>;
};

export type TextareaField = FormField & {
  __typename?: 'TextareaField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
};

export type Post4_Doc_FormFieldsUnion = TextField | SelectField | TextareaField;

export type Post4_Doc_Form = {
  __typename?: 'Post4_Doc_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<Post4_Doc_FormFieldsUnion>>>;
};

export type Body_LongTextInput = {
  raw?: Maybe<Scalars['String']>;
};

export type Post4_Doc_Input = {
  titlez?: Maybe<Scalars['String']>;
  author?: Maybe<Scalars['String']>;
  _body?: Maybe<Body_LongTextInput>;
};

export type MyBlockTemplateMyGroup_MyGroupItem_Data = {
  __typename?: 'MyBlockTemplateMyGroup_MyGroupItem_Data';
  my_group_group_item?: Maybe<Scalars['String']>;
};

export type MyBlockTemplate_MyGroup_Data = {
  __typename?: 'MyBlockTemplate_MyGroup_Data';
  my_group_item?: Maybe<MyBlockTemplateMyGroup_MyGroupItem_Data>;
};

export type MyBlockTemplate_Data = {
  __typename?: 'MyBlockTemplate_Data';
  my_tiem_name?: Maybe<Scalars['String']>;
  my_group?: Maybe<MyBlockTemplate_MyGroup_Data>;
};

export type Post3_MyBlocs_Data = MyBlockTemplate_Data;

export type Post3_Doc_Data = {
  __typename?: 'Post3_Doc_Data';
  my_titlez?: Maybe<Scalars['String']>;
  my_blocs?: Maybe<Array<Maybe<Post3_MyBlocs_Data>>>;
  _body?: Maybe<LongTextValue>;
};

export type MyBlockTemplateMyGroup_MyGroupItem_Values = {
  __typename?: 'MyBlockTemplateMyGroup_MyGroupItem_Values';
  my_group_group_item?: Maybe<Scalars['String']>;
};

export type MyBlockTemplate_MyGroup_Values = {
  __typename?: 'MyBlockTemplate_MyGroup_Values';
  my_group_item?: Maybe<MyBlockTemplateMyGroup_MyGroupItem_Values>;
};

export type MyBlockTemplate_Values = {
  __typename?: 'MyBlockTemplate_Values';
  my_tiem_name?: Maybe<Scalars['String']>;
  my_group?: Maybe<MyBlockTemplate_MyGroup_Values>;
  _template?: Maybe<Scalars['String']>;
};

export type Post3_MyBlocs_Values = MyBlockTemplate_Values;

export type Post3_Doc_Values = {
  __typename?: 'Post3_Doc_Values';
  my_titlez?: Maybe<Scalars['String']>;
  my_blocs?: Maybe<Array<Maybe<Post3_MyBlocs_Values>>>;
  _body?: Maybe<LongTextInitialValue>;
  _template?: Maybe<Scalars['String']>;
};

export type MyBlockTemplateMyGroup_MyGroupItem_FormFieldsUnion = TextField;

export type MyBlockTemplateMyGroup_MyGroupItem_GroupField = FormField & {
  __typename?: 'MyBlockTemplateMyGroup_MyGroupItem_GroupField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<MyBlockTemplateMyGroup_MyGroupItem_FormFieldsUnion>>>;
};

export type MyBlockTemplate_MyGroup_FormFieldsUnion = MyBlockTemplateMyGroup_MyGroupItem_GroupField;

export type MyBlockTemplate_MyGroup_GroupField = FormField & {
  __typename?: 'MyBlockTemplate_MyGroup_GroupField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<MyBlockTemplate_MyGroup_FormFieldsUnion>>>;
};

export type MyBlockTemplate_FormFieldsUnion = TextField | MyBlockTemplate_MyGroup_GroupField;

export type MyBlockTemplate_Form = {
  __typename?: 'MyBlockTemplate_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<MyBlockTemplate_FormFieldsUnion>>>;
};

export type Post3_MyBlocs_BlocksFieldTemplates = {
  __typename?: 'Post3_MyBlocs_BlocksFieldTemplates';
  myBlockTemplate?: Maybe<MyBlockTemplate_Form>;
};

export type Post3_MyBlocs_BlocksField = FormField & {
  __typename?: 'Post3_MyBlocs_BlocksField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  templates?: Maybe<Post3_MyBlocs_BlocksFieldTemplates>;
};

export type Post3_Doc_FormFieldsUnion = TextField | Post3_MyBlocs_BlocksField | TextareaField;

export type Post3_Doc_Form = {
  __typename?: 'Post3_Doc_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<Post3_Doc_FormFieldsUnion>>>;
};

export type MyBlockTemplateMyGroup_MyGroupItem_Input = {
  my_group_group_item?: Maybe<Scalars['String']>;
};

export type MyBlockTemplate_MyGroup_Input = {
  my_group_item?: Maybe<MyBlockTemplateMyGroup_MyGroupItem_Input>;
};

export type MyBlockTemplate_Input = {
  my_tiem_name?: Maybe<Scalars['String']>;
  my_group?: Maybe<MyBlockTemplate_MyGroup_Input>;
};

export type MyBlocs_Input = {
  myBlockTemplate?: Maybe<MyBlockTemplate_Input>;
};

export type Post3_Doc_Input = {
  my_titlez?: Maybe<Scalars['String']>;
  my_blocs?: Maybe<Array<Maybe<MyBlocs_Input>>>;
  _body?: Maybe<Body_LongTextInput>;
};


