// DO NOT MODIFY THIS FILE. This file is automatically generated by Forestry
export type Maybe<T> = T | null;
export type Exact<T extends { [key: string]: any }> = { [K in keyof T]: T[K] };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
};

export type Pages_DocumentUnion = BlockPage;

export type Pages_DocumentNode = {
  __typename?: "Pages_DocumentNode";
  path?: Maybe<Scalars["String"]>;
  relativePath?: Maybe<Scalars["String"]>;
  breadcrumbs?: Maybe<Array<Maybe<Scalars["String"]>>>;
  basename?: Maybe<Scalars["String"]>;
  extension?: Maybe<Scalars["String"]>;
  filename?: Maybe<Scalars["String"]>;
  node?: Maybe<Pages_DocumentUnion>;
};

export type Pages_DocumentNodeBreadcrumbsArgs = {
  excludeExtension?: Maybe<Scalars["Boolean"]>;
};

export type Posts_DocumentUnion = Post;

export type Posts_DocumentNode = {
  __typename?: "Posts_DocumentNode";
  path?: Maybe<Scalars["String"]>;
  relativePath?: Maybe<Scalars["String"]>;
  breadcrumbs?: Maybe<Array<Maybe<Scalars["String"]>>>;
  basename?: Maybe<Scalars["String"]>;
  extension?: Maybe<Scalars["String"]>;
  filename?: Maybe<Scalars["String"]>;
  node?: Maybe<Posts_DocumentUnion>;
};

export type Posts_DocumentNodeBreadcrumbsArgs = {
  excludeExtension?: Maybe<Scalars["Boolean"]>;
};

export type Authors_DocumentUnion = Author;

export type Authors_DocumentNode = {
  __typename?: "Authors_DocumentNode";
  path?: Maybe<Scalars["String"]>;
  relativePath?: Maybe<Scalars["String"]>;
  breadcrumbs?: Maybe<Array<Maybe<Scalars["String"]>>>;
  basename?: Maybe<Scalars["String"]>;
  extension?: Maybe<Scalars["String"]>;
  filename?: Maybe<Scalars["String"]>;
  node?: Maybe<Authors_DocumentUnion>;
};

export type Authors_DocumentNodeBreadcrumbsArgs = {
  excludeExtension?: Maybe<Scalars["Boolean"]>;
};

export type Menus_DocumentUnion = Menu;

export type Menus_DocumentNode = {
  __typename?: "Menus_DocumentNode";
  path?: Maybe<Scalars["String"]>;
  relativePath?: Maybe<Scalars["String"]>;
  breadcrumbs?: Maybe<Array<Maybe<Scalars["String"]>>>;
  basename?: Maybe<Scalars["String"]>;
  extension?: Maybe<Scalars["String"]>;
  filename?: Maybe<Scalars["String"]>;
  node?: Maybe<Menus_DocumentUnion>;
};

export type Menus_DocumentNodeBreadcrumbsArgs = {
  excludeExtension?: Maybe<Scalars["Boolean"]>;
};

export type Query = {
  __typename?: "Query";
  getPagesDocument?: Maybe<Pages_DocumentNode>;
  getPagesDocuments?: Maybe<Array<Maybe<Pages_DocumentNode>>>;
  getPostsDocument?: Maybe<Posts_DocumentNode>;
  getPostsDocuments?: Maybe<Array<Maybe<Posts_DocumentNode>>>;
  getAuthorsDocument?: Maybe<Authors_DocumentNode>;
  getAuthorsDocuments?: Maybe<Array<Maybe<Authors_DocumentNode>>>;
  getMenusDocument?: Maybe<Menus_DocumentNode>;
  getMenusDocuments?: Maybe<Array<Maybe<Menus_DocumentNode>>>;
  document?: Maybe<DocumentNode>;
  documents?: Maybe<Array<Maybe<DocumentNode>>>;
  getSections?: Maybe<Array<Maybe<SectionUnion>>>;
  getSection?: Maybe<SectionUnion>;
  documentList?: Maybe<Array<Maybe<Scalars["String"]>>>;
  documentListBySection?: Maybe<Array<Maybe<DocumentNode>>>;
  media?: Maybe<Scalars["String"]>;
  mediaList?: Maybe<Array<Maybe<Scalars["String"]>>>;
};

export type QueryGetPagesDocumentArgs = {
  relativePath?: Maybe<Scalars["String"]>;
};

export type QueryGetPagesDocumentsArgs = {
  first?: Maybe<Scalars["Int"]>;
  after?: Maybe<Scalars["String"]>;
  last?: Maybe<Scalars["Int"]>;
  before?: Maybe<Scalars["String"]>;
};

export type QueryGetPostsDocumentArgs = {
  relativePath?: Maybe<Scalars["String"]>;
};

export type QueryGetPostsDocumentsArgs = {
  first?: Maybe<Scalars["Int"]>;
  after?: Maybe<Scalars["String"]>;
  last?: Maybe<Scalars["Int"]>;
  before?: Maybe<Scalars["String"]>;
};

export type QueryGetAuthorsDocumentArgs = {
  relativePath?: Maybe<Scalars["String"]>;
};

export type QueryGetAuthorsDocumentsArgs = {
  first?: Maybe<Scalars["Int"]>;
  after?: Maybe<Scalars["String"]>;
  last?: Maybe<Scalars["Int"]>;
  before?: Maybe<Scalars["String"]>;
};

export type QueryGetMenusDocumentArgs = {
  relativePath?: Maybe<Scalars["String"]>;
};

export type QueryGetMenusDocumentsArgs = {
  first?: Maybe<Scalars["Int"]>;
  after?: Maybe<Scalars["String"]>;
  last?: Maybe<Scalars["Int"]>;
  before?: Maybe<Scalars["String"]>;
};

export type QueryDocumentArgs = {
  relativePath?: Maybe<Scalars["String"]>;
  section?: Maybe<Scalars["String"]>;
};

export type QueryDocumentsArgs = {
  section?: Maybe<Scalars["String"]>;
};

export type QueryGetSectionArgs = {
  section?: Maybe<Scalars["String"]>;
};

export type QueryDocumentListArgs = {
  directory?: Maybe<Scalars["String"]>;
};

export type QueryDocumentListBySectionArgs = {
  section?: Maybe<Scalars["String"]>;
};

export type QueryMediaArgs = {
  path?: Maybe<Scalars["String"]>;
};

export type QueryMediaListArgs = {
  directory?: Maybe<Scalars["String"]>;
};

export type Mutation = {
  __typename?: "Mutation";
  updateDocument?: Maybe<DocumentNode>;
  addPendingDocument?: Maybe<DocumentNode>;
};

export type MutationUpdateDocumentArgs = {
  relativePath?: Maybe<Scalars["String"]>;
  section?: Maybe<Scalars["String"]>;
  params?: Maybe<DocumentInput>;
};

export type MutationAddPendingDocumentArgs = {
  relativePath?: Maybe<Scalars["String"]>;
  section?: Maybe<Scalars["String"]>;
  template?: Maybe<Scalars["String"]>;
};

export type Sidecar_Cta_InputData = {
  header?: Maybe<Scalars["String"]>;
};

export type ActionVideo_InputData = {
  template?: Maybe<Scalars["String"]>;
  url?: Maybe<Scalars["String"]>;
};

export type ActionNewsletter_InputData = {
  template?: Maybe<Scalars["String"]>;
  body?: Maybe<Scalars["String"]>;
  footer?: Maybe<Scalars["String"]>;
};

export type ActionPageReference_ButtonSettings_InputData = {
  label?: Maybe<Scalars["String"]>;
};

export type ActionPageReference_InputData = {
  template?: Maybe<Scalars["String"]>;
  page?: Maybe<Scalars["String"]>;
  button_settings?: Maybe<ActionPageReference_ButtonSettings_InputData>;
};

export type ActionVideoActionNewsletterActionPageReference_DocumentInput = {
  ActionVideo_InputData?: Maybe<ActionVideo_InputData>;
  ActionNewsletter_InputData?: Maybe<ActionNewsletter_InputData>;
  ActionPageReference_InputData?: Maybe<ActionPageReference_InputData>;
};

export type Sidecar_InputData = {
  template?: Maybe<Scalars["String"]>;
  text?: Maybe<Scalars["String"]>;
  image?: Maybe<Scalars["String"]>;
  cta?: Maybe<Sidecar_Cta_InputData>;
  actions?: Maybe<
    Array<Maybe<ActionVideoActionNewsletterActionPageReference_DocumentInput>>
  >;
  style?: Maybe<Scalars["String"]>;
};

export type ExcerptPost_InputData = {
  template?: Maybe<Scalars["String"]>;
  post?: Maybe<Scalars["String"]>;
  description?: Maybe<Scalars["String"]>;
  style?: Maybe<Scalars["String"]>;
};

export type PostList_Posts_InputData = {
  post?: Maybe<Scalars["String"]>;
};

export type PostList_InputData = {
  template?: Maybe<Scalars["String"]>;
  posts?: Maybe<Array<Maybe<PostList_Posts_InputData>>>;
};

export type PriceList_Prices_InputData = {
  title?: Maybe<Scalars["String"]>;
  description?: Maybe<Scalars["String"]>;
  bullet_points?: Maybe<Array<Maybe<Scalars["String"]>>>;
  category?: Maybe<Scalars["String"]>;
};

export type PriceList_InputData = {
  template?: Maybe<Scalars["String"]>;
  heading?: Maybe<Scalars["String"]>;
  prices?: Maybe<Array<Maybe<PriceList_Prices_InputData>>>;
};

export type AuthorList_InputData = {
  template?: Maybe<Scalars["String"]>;
  authors?: Maybe<Array<Maybe<Scalars["String"]>>>;
};

export type SponsorList_Sponsor_InputData = {
  name?: Maybe<Scalars["String"]>;
  url?: Maybe<Scalars["String"]>;
  image?: Maybe<Scalars["String"]>;
};

export type SponsorList_InputData = {
  template?: Maybe<Scalars["String"]>;
  description?: Maybe<Scalars["String"]>;
  sponsor?: Maybe<Array<Maybe<SponsorList_Sponsor_InputData>>>;
};

export type PageReference_InputData = {
  template?: Maybe<Scalars["String"]>;
  description?: Maybe<Scalars["String"]>;
  page?: Maybe<Scalars["String"]>;
};

export type SectionIndex_InputData = {
  template?: Maybe<Scalars["String"]>;
  body?: Maybe<Scalars["String"]>;
  limit?: Maybe<Scalars["String"]>;
  section?: Maybe<Scalars["String"]>;
};

export type SidecarExcerptPostPostListPriceListAuthorListSponsorListPageReferenceSectionIndex_DocumentInput = {
  Sidecar_InputData?: Maybe<Sidecar_InputData>;
  ExcerptPost_InputData?: Maybe<ExcerptPost_InputData>;
  PostList_InputData?: Maybe<PostList_InputData>;
  PriceList_InputData?: Maybe<PriceList_InputData>;
  AuthorList_InputData?: Maybe<AuthorList_InputData>;
  SponsorList_InputData?: Maybe<SponsorList_InputData>;
  PageReference_InputData?: Maybe<PageReference_InputData>;
  SectionIndex_InputData?: Maybe<SectionIndex_InputData>;
};

export type BlockPage_InputData = {
  title?: Maybe<Scalars["String"]>;
  date?: Maybe<Scalars["String"]>;
  blocks?: Maybe<
    Array<
      Maybe<
        SidecarExcerptPostPostListPriceListAuthorListSponsorListPageReferenceSectionIndex_DocumentInput
      >
    >
  >;
};

export type BlockPage_Input = {
  data?: Maybe<BlockPage_InputData>;
  content?: Maybe<Scalars["String"]>;
};

export type Post_InputData = {
  title?: Maybe<Scalars["String"]>;
  author?: Maybe<Scalars["String"]>;
  image?: Maybe<Scalars["String"]>;
  hashtags?: Maybe<Array<Maybe<Scalars["String"]>>>;
};

export type Post_Input = {
  data?: Maybe<Post_InputData>;
  content?: Maybe<Scalars["String"]>;
};

export type Author_Accolades_InputData = {
  figure?: Maybe<Scalars["String"]>;
  description?: Maybe<Scalars["String"]>;
};

export type Author_InputData = {
  name?: Maybe<Scalars["String"]>;
  image?: Maybe<Scalars["String"]>;
  gallery?: Maybe<Array<Maybe<Scalars["String"]>>>;
  anecdotes?: Maybe<Array<Maybe<Scalars["String"]>>>;
  accolades?: Maybe<Array<Maybe<Author_Accolades_InputData>>>;
};

export type Author_Input = {
  data?: Maybe<Author_InputData>;
  content?: Maybe<Scalars["String"]>;
};

export type Menu_MenuItem_InputData = {
  label?: Maybe<Scalars["String"]>;
  page?: Maybe<Scalars["String"]>;
};

export type Menu_InputData = {
  logo?: Maybe<Scalars["String"]>;
  menu_item?: Maybe<Array<Maybe<Menu_MenuItem_InputData>>>;
};

export type Menu_Input = {
  data?: Maybe<Menu_InputData>;
  content?: Maybe<Scalars["String"]>;
};

export type DocumentInput = {
  BlockPage_Input?: Maybe<BlockPage_Input>;
  Post_Input?: Maybe<Post_Input>;
  Author_Input?: Maybe<Author_Input>;
  Menu_Input?: Maybe<Menu_Input>;
};

export type TextField = {
  __typename?: "TextField";
  name?: Maybe<Scalars["String"]>;
  label?: Maybe<Scalars["String"]>;
  component?: Maybe<Scalars["String"]>;
};

export type DatetimeField = {
  __typename?: "DatetimeField";
  name?: Maybe<Scalars["String"]>;
  label?: Maybe<Scalars["String"]>;
  component?: Maybe<Scalars["String"]>;
};

export type TextareaField = {
  __typename?: "TextareaField";
  name?: Maybe<Scalars["String"]>;
  label?: Maybe<Scalars["String"]>;
  component?: Maybe<Scalars["String"]>;
};

export type FileField = {
  __typename?: "FileField";
  name?: Maybe<Scalars["String"]>;
  label?: Maybe<Scalars["String"]>;
  component?: Maybe<Scalars["String"]>;
};

export type Sidecar_Cta_FormFields = TextField;

export type Sidecar_Cta_GroupField = {
  __typename?: "Sidecar_Cta_GroupField";
  name?: Maybe<Scalars["String"]>;
  label?: Maybe<Scalars["String"]>;
  component?: Maybe<Scalars["String"]>;
  fields?: Maybe<Array<Maybe<Sidecar_Cta_FormFields>>>;
};

export type ActionVideo_FormFields = TextField;

export type ActionVideo_Form = {
  __typename?: "ActionVideo_Form";
  label?: Maybe<Scalars["String"]>;
  name?: Maybe<Scalars["String"]>;
  fields?: Maybe<Array<Maybe<ActionVideo_FormFields>>>;
};

export type ActionNewsletter_FormFields = TextareaField;

export type ActionNewsletter_Form = {
  __typename?: "ActionNewsletter_Form";
  label?: Maybe<Scalars["String"]>;
  name?: Maybe<Scalars["String"]>;
  fields?: Maybe<Array<Maybe<ActionNewsletter_FormFields>>>;
};

export type SelectField = {
  __typename?: "SelectField";
  name?: Maybe<Scalars["String"]>;
  label?: Maybe<Scalars["String"]>;
  component?: Maybe<Scalars["String"]>;
  options?: Maybe<Array<Maybe<Scalars["String"]>>>;
};

export type ActionPageReference_ButtonSettings_FormFields = TextField;

export type ActionPageReference_ButtonSettings_GroupField = {
  __typename?: "ActionPageReference_ButtonSettings_GroupField";
  name?: Maybe<Scalars["String"]>;
  label?: Maybe<Scalars["String"]>;
  component?: Maybe<Scalars["String"]>;
  fields?: Maybe<Array<Maybe<ActionPageReference_ButtonSettings_FormFields>>>;
};

export type ActionPageReference_FormFields =
  | SelectField
  | ActionPageReference_ButtonSettings_GroupField;

export type ActionPageReference_Form = {
  __typename?: "ActionPageReference_Form";
  label?: Maybe<Scalars["String"]>;
  name?: Maybe<Scalars["String"]>;
  fields?: Maybe<Array<Maybe<ActionPageReference_FormFields>>>;
};

export type Sidecar_Actions_BlocksFieldTemplates = {
  __typename?: "Sidecar_Actions_BlocksFieldTemplates";
  actionVideo?: Maybe<ActionVideo_Form>;
  actionNewsletter?: Maybe<ActionNewsletter_Form>;
  actionPageReference?: Maybe<ActionPageReference_Form>;
};

export type Sidecar_Actions_BlocksField = {
  __typename?: "Sidecar_Actions_BlocksField";
  name?: Maybe<Scalars["String"]>;
  label?: Maybe<Scalars["String"]>;
  component?: Maybe<Scalars["String"]>;
  templates?: Maybe<Sidecar_Actions_BlocksFieldTemplates>;
};

export type Sidecar_FormFields =
  | TextareaField
  | FileField
  | Sidecar_Cta_GroupField
  | Sidecar_Actions_BlocksField
  | SelectField;

export type Sidecar_Form = {
  __typename?: "Sidecar_Form";
  label?: Maybe<Scalars["String"]>;
  name?: Maybe<Scalars["String"]>;
  fields?: Maybe<Array<Maybe<Sidecar_FormFields>>>;
};

export type ExcerptPost_FormFields = SelectField | TextareaField;

export type ExcerptPost_Form = {
  __typename?: "ExcerptPost_Form";
  label?: Maybe<Scalars["String"]>;
  name?: Maybe<Scalars["String"]>;
  fields?: Maybe<Array<Maybe<ExcerptPost_FormFields>>>;
};

export type PostList_Posts_FormFields = SelectField;

export type PostList_Posts_GroupListField = {
  __typename?: "PostList_Posts_GroupListField";
  name?: Maybe<Scalars["String"]>;
  label?: Maybe<Scalars["String"]>;
  component?: Maybe<Scalars["String"]>;
  fields?: Maybe<Array<Maybe<PostList_Posts_FormFields>>>;
};

export type PostList_FormFields = PostList_Posts_GroupListField;

export type PostList_Form = {
  __typename?: "PostList_Form";
  label?: Maybe<Scalars["String"]>;
  name?: Maybe<Scalars["String"]>;
  fields?: Maybe<Array<Maybe<PostList_FormFields>>>;
};

export type List_FormFieldsUnion = TextField | SelectField;

export type ListField = {
  __typename?: "ListField";
  name?: Maybe<Scalars["String"]>;
  label?: Maybe<Scalars["String"]>;
  component?: Maybe<Scalars["String"]>;
  defaultItem?: Maybe<Scalars["String"]>;
  field?: Maybe<List_FormFieldsUnion>;
};

export type PriceList_Prices_FormFields =
  | TextField
  | TextareaField
  | ListField
  | SelectField;

export type PriceList_Prices_GroupListField = {
  __typename?: "PriceList_Prices_GroupListField";
  name?: Maybe<Scalars["String"]>;
  label?: Maybe<Scalars["String"]>;
  component?: Maybe<Scalars["String"]>;
  fields?: Maybe<Array<Maybe<PriceList_Prices_FormFields>>>;
};

export type PriceList_FormFields =
  | TextareaField
  | PriceList_Prices_GroupListField;

export type PriceList_Form = {
  __typename?: "PriceList_Form";
  label?: Maybe<Scalars["String"]>;
  name?: Maybe<Scalars["String"]>;
  fields?: Maybe<Array<Maybe<PriceList_FormFields>>>;
};

export type AuthorList_FormFields = ListField;

export type AuthorList_Form = {
  __typename?: "AuthorList_Form";
  label?: Maybe<Scalars["String"]>;
  name?: Maybe<Scalars["String"]>;
  fields?: Maybe<Array<Maybe<AuthorList_FormFields>>>;
};

export type SponsorList_Sponsor_FormFields = TextField | FileField;

export type SponsorList_Sponsor_GroupListField = {
  __typename?: "SponsorList_Sponsor_GroupListField";
  name?: Maybe<Scalars["String"]>;
  label?: Maybe<Scalars["String"]>;
  component?: Maybe<Scalars["String"]>;
  fields?: Maybe<Array<Maybe<SponsorList_Sponsor_FormFields>>>;
};

export type SponsorList_FormFields =
  | TextareaField
  | SponsorList_Sponsor_GroupListField;

export type SponsorList_Form = {
  __typename?: "SponsorList_Form";
  label?: Maybe<Scalars["String"]>;
  name?: Maybe<Scalars["String"]>;
  fields?: Maybe<Array<Maybe<SponsorList_FormFields>>>;
};

export type PageReference_FormFields = TextareaField | SelectField;

export type PageReference_Form = {
  __typename?: "PageReference_Form";
  label?: Maybe<Scalars["String"]>;
  name?: Maybe<Scalars["String"]>;
  fields?: Maybe<Array<Maybe<PageReference_FormFields>>>;
};

export type NumberField = {
  __typename?: "NumberField";
  name?: Maybe<Scalars["String"]>;
  label?: Maybe<Scalars["String"]>;
  component?: Maybe<Scalars["String"]>;
};

export type SectionIndex_FormFields = TextareaField | NumberField | SelectField;

export type SectionIndex_Form = {
  __typename?: "SectionIndex_Form";
  label?: Maybe<Scalars["String"]>;
  name?: Maybe<Scalars["String"]>;
  fields?: Maybe<Array<Maybe<SectionIndex_FormFields>>>;
};

export type BlockPage_Blocks_BlocksFieldTemplates = {
  __typename?: "BlockPage_Blocks_BlocksFieldTemplates";
  sidecar?: Maybe<Sidecar_Form>;
  excerptPost?: Maybe<ExcerptPost_Form>;
  postList?: Maybe<PostList_Form>;
  priceList?: Maybe<PriceList_Form>;
  authorList?: Maybe<AuthorList_Form>;
  sponsorList?: Maybe<SponsorList_Form>;
  pageReference?: Maybe<PageReference_Form>;
  sectionIndex?: Maybe<SectionIndex_Form>;
};

export type BlockPage_Blocks_BlocksField = {
  __typename?: "BlockPage_Blocks_BlocksField";
  name?: Maybe<Scalars["String"]>;
  label?: Maybe<Scalars["String"]>;
  component?: Maybe<Scalars["String"]>;
  templates?: Maybe<BlockPage_Blocks_BlocksFieldTemplates>;
};

export type BlockPage_FormFields =
  | TextField
  | DatetimeField
  | BlockPage_Blocks_BlocksField;

export type BlockPage_Form = {
  __typename?: "BlockPage_Form";
  label?: Maybe<Scalars["String"]>;
  name?: Maybe<Scalars["String"]>;
  fields?: Maybe<Array<Maybe<BlockPage_FormFields>>>;
};

export type LongTextValue = {
  __typename?: "LongTextValue";
  raw?: Maybe<Scalars["String"]>;
  markdownAst?: Maybe<Scalars["String"]>;
  html?: Maybe<Scalars["String"]>;
};

export type Sidecar_Cta_Data = {
  __typename?: "Sidecar_Cta_Data";
  header?: Maybe<Scalars["String"]>;
};

export type ActionVideo_Data = {
  __typename?: "ActionVideo_Data";
  url?: Maybe<Scalars["String"]>;
};

export type ActionNewsletter_Data = {
  __typename?: "ActionNewsletter_Data";
  body?: Maybe<LongTextValue>;
  footer?: Maybe<LongTextValue>;
};

export type ActionPageReference_ButtonSettings_Data = {
  __typename?: "ActionPageReference_ButtonSettings_Data";
  label?: Maybe<Scalars["String"]>;
};

export type ActionPageReference_Data = {
  __typename?: "ActionPageReference_Data";
  page?: Maybe<Pages_DocumentNode>;
  button_settings?: Maybe<ActionPageReference_ButtonSettings_Data>;
};

export type ActionVideo_ActionNewsletter_ActionPageReference_DataUnion =
  | ActionVideo_Data
  | ActionNewsletter_Data
  | ActionPageReference_Data;

export type Sidecar_Data = {
  __typename?: "Sidecar_Data";
  text?: Maybe<LongTextValue>;
  image?: Maybe<Scalars["String"]>;
  cta?: Maybe<Sidecar_Cta_Data>;
  actions?: Maybe<
    Array<Maybe<ActionVideo_ActionNewsletter_ActionPageReference_DataUnion>>
  >;
  style?: Maybe<Scalars["String"]>;
};

export type ExcerptPost_Data = {
  __typename?: "ExcerptPost_Data";
  post?: Maybe<Posts_DocumentNode>;
  description?: Maybe<LongTextValue>;
  style?: Maybe<Scalars["String"]>;
};

export type PostList_Posts_Data = {
  __typename?: "PostList_Posts_Data";
  post?: Maybe<Posts_DocumentNode>;
};

export type PostList_Data = {
  __typename?: "PostList_Data";
  posts?: Maybe<Array<Maybe<PostList_Posts_Data>>>;
};

export type PriceList_Prices_Data = {
  __typename?: "PriceList_Prices_Data";
  title?: Maybe<Scalars["String"]>;
  description?: Maybe<LongTextValue>;
  bullet_points?: Maybe<Array<Maybe<Scalars["String"]>>>;
  category?: Maybe<Scalars["String"]>;
};

export type PriceList_Data = {
  __typename?: "PriceList_Data";
  heading?: Maybe<LongTextValue>;
  prices?: Maybe<Array<Maybe<PriceList_Prices_Data>>>;
};

export type AuthorList_Data = {
  __typename?: "AuthorList_Data";
  authors?: Maybe<Array<Maybe<Authors_DocumentNode>>>;
};

export type SponsorList_Sponsor_Data = {
  __typename?: "SponsorList_Sponsor_Data";
  name?: Maybe<Scalars["String"]>;
  url?: Maybe<Scalars["String"]>;
  image?: Maybe<Scalars["String"]>;
};

export type SponsorList_Data = {
  __typename?: "SponsorList_Data";
  description?: Maybe<LongTextValue>;
  sponsor?: Maybe<Array<Maybe<SponsorList_Sponsor_Data>>>;
};

export type PageReference_Data = {
  __typename?: "PageReference_Data";
  description?: Maybe<LongTextValue>;
  page?: Maybe<Pages_DocumentNode>;
};

export type SectionIndex_Data = {
  __typename?: "SectionIndex_Data";
  body?: Maybe<LongTextValue>;
  limit?: Maybe<Scalars["String"]>;
  section?: Maybe<Scalars["String"]>;
};

export type Sidecar_ExcerptPost_PostList_PriceList_AuthorList_SponsorList_PageReference_SectionIndex_DataUnion =
  | Sidecar_Data
  | ExcerptPost_Data
  | PostList_Data
  | PriceList_Data
  | AuthorList_Data
  | SponsorList_Data
  | PageReference_Data
  | SectionIndex_Data;

export type BlockPage_Data = {
  __typename?: "BlockPage_Data";
  title?: Maybe<Scalars["String"]>;
  date?: Maybe<Scalars["String"]>;
  blocks?: Maybe<
    Array<
      Maybe<
        Sidecar_ExcerptPost_PostList_PriceList_AuthorList_SponsorList_PageReference_SectionIndex_DataUnion
      >
    >
  >;
};

export type Sidecar_Cta_InitialValues = {
  __typename?: "Sidecar_Cta_InitialValues";
  header?: Maybe<Scalars["String"]>;
};

export type ActionVideo_InitialValues = {
  __typename?: "ActionVideo_InitialValues";
  _template?: Maybe<Scalars["String"]>;
  url?: Maybe<Scalars["String"]>;
};

export type ActionNewsletter_InitialValues = {
  __typename?: "ActionNewsletter_InitialValues";
  _template?: Maybe<Scalars["String"]>;
  body?: Maybe<Scalars["String"]>;
  footer?: Maybe<Scalars["String"]>;
};

export type ActionPageReference_ButtonSettings_InitialValues = {
  __typename?: "ActionPageReference_ButtonSettings_InitialValues";
  label?: Maybe<Scalars["String"]>;
};

export type ActionPageReference_InitialValues = {
  __typename?: "ActionPageReference_InitialValues";
  _template?: Maybe<Scalars["String"]>;
  page?: Maybe<Scalars["String"]>;
  button_settings?: Maybe<ActionPageReference_ButtonSettings_InitialValues>;
};

export type ActionVideo_ActionNewsletter_ActionPageReference_InitialValuesUnion =
  | ActionVideo_InitialValues
  | ActionNewsletter_InitialValues
  | ActionPageReference_InitialValues;

export type Sidecar_InitialValues = {
  __typename?: "Sidecar_InitialValues";
  _template?: Maybe<Scalars["String"]>;
  text?: Maybe<Scalars["String"]>;
  image?: Maybe<Scalars["String"]>;
  cta?: Maybe<Sidecar_Cta_InitialValues>;
  actions?: Maybe<
    Array<
      Maybe<ActionVideo_ActionNewsletter_ActionPageReference_InitialValuesUnion>
    >
  >;
  style?: Maybe<Scalars["String"]>;
};

export type ExcerptPost_InitialValues = {
  __typename?: "ExcerptPost_InitialValues";
  _template?: Maybe<Scalars["String"]>;
  post?: Maybe<Scalars["String"]>;
  description?: Maybe<Scalars["String"]>;
  style?: Maybe<Scalars["String"]>;
};

export type PostList_Posts_InitialValues = {
  __typename?: "PostList_Posts_InitialValues";
  post?: Maybe<Scalars["String"]>;
};

export type PostList_InitialValues = {
  __typename?: "PostList_InitialValues";
  _template?: Maybe<Scalars["String"]>;
  posts?: Maybe<Array<Maybe<PostList_Posts_InitialValues>>>;
};

export type PriceList_Prices_InitialValues = {
  __typename?: "PriceList_Prices_InitialValues";
  title?: Maybe<Scalars["String"]>;
  description?: Maybe<Scalars["String"]>;
  bullet_points?: Maybe<Array<Maybe<Scalars["String"]>>>;
  category?: Maybe<Scalars["String"]>;
};

export type PriceList_InitialValues = {
  __typename?: "PriceList_InitialValues";
  _template?: Maybe<Scalars["String"]>;
  heading?: Maybe<Scalars["String"]>;
  prices?: Maybe<Array<Maybe<PriceList_Prices_InitialValues>>>;
};

export type AuthorList_InitialValues = {
  __typename?: "AuthorList_InitialValues";
  _template?: Maybe<Scalars["String"]>;
  authors?: Maybe<Array<Maybe<Scalars["String"]>>>;
};

export type SponsorList_Sponsor_InitialValues = {
  __typename?: "SponsorList_Sponsor_InitialValues";
  name?: Maybe<Scalars["String"]>;
  url?: Maybe<Scalars["String"]>;
  image?: Maybe<Scalars["String"]>;
};

export type SponsorList_InitialValues = {
  __typename?: "SponsorList_InitialValues";
  _template?: Maybe<Scalars["String"]>;
  description?: Maybe<Scalars["String"]>;
  sponsor?: Maybe<Array<Maybe<SponsorList_Sponsor_InitialValues>>>;
};

export type PageReference_InitialValues = {
  __typename?: "PageReference_InitialValues";
  _template?: Maybe<Scalars["String"]>;
  description?: Maybe<Scalars["String"]>;
  page?: Maybe<Scalars["String"]>;
};

export type SectionIndex_InitialValues = {
  __typename?: "SectionIndex_InitialValues";
  _template?: Maybe<Scalars["String"]>;
  body?: Maybe<Scalars["String"]>;
  limit?: Maybe<Scalars["String"]>;
  section?: Maybe<Scalars["String"]>;
};

export type Sidecar_ExcerptPost_PostList_PriceList_AuthorList_SponsorList_PageReference_SectionIndex_InitialValuesUnion =
  | Sidecar_InitialValues
  | ExcerptPost_InitialValues
  | PostList_InitialValues
  | PriceList_InitialValues
  | AuthorList_InitialValues
  | SponsorList_InitialValues
  | PageReference_InitialValues
  | SectionIndex_InitialValues;

export type BlockPage_InitialValues = {
  __typename?: "BlockPage_InitialValues";
  title?: Maybe<Scalars["String"]>;
  date?: Maybe<Scalars["String"]>;
  blocks?: Maybe<
    Array<
      Maybe<
        Sidecar_ExcerptPost_PostList_PriceList_AuthorList_SponsorList_PageReference_SectionIndex_InitialValuesUnion
      >
    >
  >;
};

export type BlockPage = {
  __typename?: "BlockPage";
  form?: Maybe<BlockPage_Form>;
  data?: Maybe<BlockPage_Data>;
  initialValues?: Maybe<BlockPage_InitialValues>;
};

export type TagListField = {
  __typename?: "TagListField";
  name?: Maybe<Scalars["String"]>;
  label?: Maybe<Scalars["String"]>;
  component?: Maybe<Scalars["String"]>;
};

export type Post_FormFields =
  | TextField
  | SelectField
  | FileField
  | TagListField;

export type Post_Form = {
  __typename?: "Post_Form";
  label?: Maybe<Scalars["String"]>;
  name?: Maybe<Scalars["String"]>;
  fields?: Maybe<Array<Maybe<Post_FormFields>>>;
};

export type Post_Data = {
  __typename?: "Post_Data";
  title?: Maybe<Scalars["String"]>;
  author?: Maybe<Authors_DocumentNode>;
  image?: Maybe<Scalars["String"]>;
  hashtags?: Maybe<Array<Maybe<Scalars["String"]>>>;
};

export type Post_InitialValues = {
  __typename?: "Post_InitialValues";
  title?: Maybe<Scalars["String"]>;
  author?: Maybe<Scalars["String"]>;
  image?: Maybe<Scalars["String"]>;
  hashtags?: Maybe<Array<Maybe<Scalars["String"]>>>;
};

export type Post = {
  __typename?: "Post";
  form?: Maybe<Post_Form>;
  data?: Maybe<Post_Data>;
  initialValues?: Maybe<Post_InitialValues>;
};

export type Author_Accolades_FormFields = TextField;

export type Author_Accolades_GroupListField = {
  __typename?: "Author_Accolades_GroupListField";
  name?: Maybe<Scalars["String"]>;
  label?: Maybe<Scalars["String"]>;
  component?: Maybe<Scalars["String"]>;
  fields?: Maybe<Array<Maybe<Author_Accolades_FormFields>>>;
};

export type Author_FormFields =
  | TextField
  | FileField
  | ListField
  | Author_Accolades_GroupListField;

export type Author_Form = {
  __typename?: "Author_Form";
  label?: Maybe<Scalars["String"]>;
  name?: Maybe<Scalars["String"]>;
  fields?: Maybe<Array<Maybe<Author_FormFields>>>;
};

export type Author_Accolades_Data = {
  __typename?: "Author_Accolades_Data";
  figure?: Maybe<Scalars["String"]>;
  description?: Maybe<Scalars["String"]>;
};

export type Author_Data = {
  __typename?: "Author_Data";
  name?: Maybe<Scalars["String"]>;
  image?: Maybe<Scalars["String"]>;
  gallery?: Maybe<Array<Maybe<Scalars["String"]>>>;
  anecdotes?: Maybe<Array<Maybe<Scalars["String"]>>>;
  accolades?: Maybe<Array<Maybe<Author_Accolades_Data>>>;
};

export type Author_Accolades_InitialValues = {
  __typename?: "Author_Accolades_InitialValues";
  figure?: Maybe<Scalars["String"]>;
  description?: Maybe<Scalars["String"]>;
};

export type Author_InitialValues = {
  __typename?: "Author_InitialValues";
  name?: Maybe<Scalars["String"]>;
  image?: Maybe<Scalars["String"]>;
  gallery?: Maybe<Array<Maybe<Scalars["String"]>>>;
  anecdotes?: Maybe<Array<Maybe<Scalars["String"]>>>;
  accolades?: Maybe<Array<Maybe<Author_Accolades_InitialValues>>>;
};

export type Author = {
  __typename?: "Author";
  form?: Maybe<Author_Form>;
  data?: Maybe<Author_Data>;
  initialValues?: Maybe<Author_InitialValues>;
};

export type Menu_MenuItem_FormFields = TextField | SelectField;

export type Menu_MenuItem_GroupListField = {
  __typename?: "Menu_MenuItem_GroupListField";
  name?: Maybe<Scalars["String"]>;
  label?: Maybe<Scalars["String"]>;
  component?: Maybe<Scalars["String"]>;
  fields?: Maybe<Array<Maybe<Menu_MenuItem_FormFields>>>;
};

export type Menu_FormFields = FileField | Menu_MenuItem_GroupListField;

export type Menu_Form = {
  __typename?: "Menu_Form";
  label?: Maybe<Scalars["String"]>;
  name?: Maybe<Scalars["String"]>;
  fields?: Maybe<Array<Maybe<Menu_FormFields>>>;
};

export type Menu_MenuItem_Data = {
  __typename?: "Menu_MenuItem_Data";
  label?: Maybe<Scalars["String"]>;
  page?: Maybe<Pages_DocumentNode>;
};

export type Menu_Data = {
  __typename?: "Menu_Data";
  logo?: Maybe<Scalars["String"]>;
  menu_item?: Maybe<Array<Maybe<Menu_MenuItem_Data>>>;
};

export type Menu_MenuItem_InitialValues = {
  __typename?: "Menu_MenuItem_InitialValues";
  label?: Maybe<Scalars["String"]>;
  page?: Maybe<Scalars["String"]>;
};

export type Menu_InitialValues = {
  __typename?: "Menu_InitialValues";
  logo?: Maybe<Scalars["String"]>;
  menu_item?: Maybe<Array<Maybe<Menu_MenuItem_InitialValues>>>;
};

export type Menu = {
  __typename?: "Menu";
  form?: Maybe<Menu_Form>;
  data?: Maybe<Menu_Data>;
  initialValues?: Maybe<Menu_InitialValues>;
};

export type DocumentUnion = BlockPage | Post | Author | Menu;

export type DocumentNode = {
  __typename?: "DocumentNode";
  path?: Maybe<Scalars["String"]>;
  relativePath?: Maybe<Scalars["String"]>;
  breadcrumbs?: Maybe<Array<Maybe<Scalars["String"]>>>;
  basename?: Maybe<Scalars["String"]>;
  extension?: Maybe<Scalars["String"]>;
  filename?: Maybe<Scalars["String"]>;
  node?: Maybe<DocumentUnion>;
};

export type DocumentNodeBreadcrumbsArgs = {
  excludeExtension?: Maybe<Scalars["Boolean"]>;
};

export type SectionUnion = {
  __typename?: "SectionUnion";
  type?: Maybe<Scalars["String"]>;
  path?: Maybe<Scalars["String"]>;
  label?: Maybe<Scalars["String"]>;
  create?: Maybe<Scalars["String"]>;
  match?: Maybe<Scalars["String"]>;
  templates?: Maybe<Array<Maybe<Scalars["String"]>>>;
  slug?: Maybe<Scalars["String"]>;
  documents?: Maybe<Array<Maybe<DocumentNode>>>;
};

export type Pages_DocumentNodeUnion = BlockPage;

export type Pages_Section = {
  __typename?: "Pages_Section";
  path?: Maybe<Scalars["String"]>;
  relativePath?: Maybe<Scalars["String"]>;
  breadcrumbs?: Maybe<Array<Maybe<Scalars["String"]>>>;
  basename?: Maybe<Scalars["String"]>;
  extension?: Maybe<Scalars["String"]>;
  filename?: Maybe<Scalars["String"]>;
  node?: Maybe<Pages_DocumentNodeUnion>;
};

export type Pages_SectionBreadcrumbsArgs = {
  excludeExtension?: Maybe<Scalars["Boolean"]>;
};

export type Posts_DocumentNodeUnion = Post;

export type Posts_Section = {
  __typename?: "Posts_Section";
  path?: Maybe<Scalars["String"]>;
  relativePath?: Maybe<Scalars["String"]>;
  breadcrumbs?: Maybe<Array<Maybe<Scalars["String"]>>>;
  basename?: Maybe<Scalars["String"]>;
  extension?: Maybe<Scalars["String"]>;
  filename?: Maybe<Scalars["String"]>;
  node?: Maybe<Posts_DocumentNodeUnion>;
};

export type Posts_SectionBreadcrumbsArgs = {
  excludeExtension?: Maybe<Scalars["Boolean"]>;
};

export type Authors_DocumentNodeUnion = Author;

export type Authors_Section = {
  __typename?: "Authors_Section";
  path?: Maybe<Scalars["String"]>;
  relativePath?: Maybe<Scalars["String"]>;
  breadcrumbs?: Maybe<Array<Maybe<Scalars["String"]>>>;
  basename?: Maybe<Scalars["String"]>;
  extension?: Maybe<Scalars["String"]>;
  filename?: Maybe<Scalars["String"]>;
  node?: Maybe<Authors_DocumentNodeUnion>;
};

export type Authors_SectionBreadcrumbsArgs = {
  excludeExtension?: Maybe<Scalars["Boolean"]>;
};

export type Menus_DocumentNodeUnion = Menu;

export type Menus_Section = {
  __typename?: "Menus_Section";
  path?: Maybe<Scalars["String"]>;
  relativePath?: Maybe<Scalars["String"]>;
  breadcrumbs?: Maybe<Array<Maybe<Scalars["String"]>>>;
  basename?: Maybe<Scalars["String"]>;
  extension?: Maybe<Scalars["String"]>;
  filename?: Maybe<Scalars["String"]>;
  node?: Maybe<Menus_DocumentNodeUnion>;
};

export type Menus_SectionBreadcrumbsArgs = {
  excludeExtension?: Maybe<Scalars["Boolean"]>;
};

export type DocumentNodeUnion =
  | Pages_Section
  | Posts_Section
  | Authors_Section
  | Menus_Section;

import { useForestryForm } from "@forestryio/client";

export const useForestryForm2 = (
  props,
  options?: {
    onSubmit: any;
  }
) => {
  return useForestryForm<DocumentUnion>(props, options);
};
