query DocumentQuery($path: String!) {
  undefined(path: $path) {
    ... on BlockPage {
      form {
        label
        key
        fields {
          ... on TextFormField {
            name
            label
            description
            component
          }
          ... on BlocksFieldConfig {
            name
            label
            description
            component
            templates {
              SidecarFieldConfig {
                label
                key
                fields {
                  __typename
                  ... on ImageFormField {
                    name
                    label
                    description
                    component
                    fields {
                      name
                      label
                      component
                    }
                  }
                  ... on CtaFieldsListSidecarConfig {
                    label
                    key
                    name
                    component
                    fields {
                      __typename
                    }
                  }
                  ... on ActionsFieldConfig {
                    name
                    label
                    description
                    component
                    templates {
                      ActionVideoFieldConfig {
                        label
                        key
                        fields {
                          __typename
                        }
                      }
                      ActionNewsletterFieldConfig {
                        label
                        key
                        fields {
                          __typename
                        }
                      }
                      ActionPageReferenceFieldConfig {
                        label
                        key
                        fields {
                          ... on SelectFormField {
                            name
                            label
                            description
                            component
                            options
                          }
                          ... on ButtonSettingsFieldsListActionPageReferenceConfig {
                            label
                            key
                            name
                            component
                            fields {
                              __typename
                            }
                          }
                        }
                      }
                    }
                  }
                  __typename
                }
              }
              ExcerptPostFieldConfig {
                label
                key
                fields {
                  __typename
                  __typename
                }
              }
              PostListFieldConfig {
                label
                key
                fields {
                  ... on PostsFieldsListPostListConfig {
                    label
                    key
                    name
                    component
                    fields {
                      __typename
                    }
                  }
                }
              }
              PriceListFieldConfig {
                label
                key
                fields {
                  __typename
                  ... on PricesFieldsListPriceListConfig {
                    label
                    key
                    name
                    component
                    fields {
                      __typename
                      ... on BulletPointsListPriceListPricesConfig {
                        name
                        label
                        description
                        component
                        itemField {
                          name
                          label
                          component
                        }
                      }
                      __typename
                    }
                  }
                }
              }
              AuthorListFieldConfig {
                label
                key
                fields {
                  ... on AuthorsListAuthorListConfig {
                    name
                    label
                    description
                    component
                    fields {
                      name
                      label
                      component
                      options
                    }
                  }
                }
              }
              SponsorListFieldConfig {
                label
                key
                fields {
                  __typename
                  ... on SponsorFieldsListSponsorListConfig {
                    label
                    key
                    name
                    component
                    fields {
                      __typename
                      __typename
                    }
                  }
                }
              }
              PageReferenceFieldConfig {
                label
                key
                fields {
                  __typename
                  __typename
                }
              }
              SectionIndexFieldConfig {
                label
                key
                fields {
                  __typename
                  __typename
                }
              }
            }
          }
        }
      }
      absolutePath
      path
      content
      excerpt
      data {
        _template
        title
        blocks {
          ... on SidecarData {
            _template
            text
            image {
              path
              absolutePath
            }
            cta {
              header
            }
            actions {
              ... on ActionVideoData {
                _template
                url
              }
              ... on ActionNewsletterData {
                _template
                body
                footer
              }
              ... on ActionPageReferenceData {
                _template
                page {
                  __typename
                }
                button_settings {
                  label
                }
              }
            }
            style
          }
          ... on ExcerptPostData {
            _template
            post {
              ... on Post {
                form {
                  label
                  key
                  fields {
                    __typename
                    __typename
                    __typename
                    ... on TagsFormField {
                      name
                      label
                      description
                      component
                    }
                  }
                }
                absolutePath
                path
                content
                excerpt
                data {
                  _template
                  title
                  author {
                    ... on Author {
                      form {
                        label
                        key
                        fields {
                          __typename
                          __typename
                          ... on AnecdotesListAuthorConfig {
                            name
                            label
                            description
                            component
                            itemField {
                              name
                              label
                              component
                            }
                          }
                          ... on AccoladesFieldsListAuthorConfig {
                            label
                            key
                            name
                            component
                            fields {
                              __typename
                            }
                          }
                        }
                      }
                      absolutePath
                      path
                      content
                      excerpt
                      data {
                        _template
                        name
                        image {
                          path
                          absolutePath
                        }
                        gallery {
                          path
                          absolutePath
                        }
                        anecdotes
                        accolades {
                          figure
                          description
                        }
                      }
                    }
                  }
                  image {
                    path
                    absolutePath
                  }
                  hashtags
                }
              }
            }
            description
            style
          }
          ... on PostListData {
            _template
            posts {
              post {
                __typename
              }
            }
          }
          ... on PriceListData {
            _template
            heading
            prices {
              title
              description
              bullet_points
              category
            }
          }
          ... on AuthorListData {
            _template
            authors {
              __typename
            }
          }
          ... on SponsorListData {
            _template
            description
            sponsor {
              name
              url
              image {
                path
                absolutePath
              }
            }
          }
          ... on PageReferenceData {
            _template
            description
            page {
              __typename
            }
          }
          ... on SectionIndexData {
            _template
            body
            limit
            section
          }
        }
      }
    }
    __typename
    __typename
    ... on Menu {
      form {
        label
        key
        fields {
          __typename
          ... on MenuItemFieldsListMenuConfig {
            label
            key
            name
            component
            fields {
              __typename
              __typename
            }
          }
        }
      }
      absolutePath
      path
      content
      excerpt
      data {
        _template
        logo {
          path
          absolutePath
        }
        menu_item {
          label
          page {
            __typename
          }
        }
      }
    }
  }
}
