// DO NOT MODIFY THIS FILE. This file is automatically generated by Forestry
export type Maybe<T> = T | null;
export type Exact<T extends { [key: string]: any }> = { [K in keyof T]: T[K] };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
};

export type Query = {
  __typename?: 'Query';
  document?: Maybe<DocumentUnion>;
};


export type QueryDocumentArgs = {
  path: Scalars['String'];
};

export type DocumentUnion = BlockPage | Post | Author | Menu;

export type BlockPage = {
  __typename?: 'BlockPage';
  form?: Maybe<BlockPageFieldConfig>;
  absolutePath?: Maybe<Scalars['String']>;
  path: Scalars['String'];
  content: Scalars['String'];
  excerpt?: Maybe<Scalars['String']>;
  data: BlockPageData;
};

export type BlockPageFieldConfig = {
  __typename?: 'BlockPageFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<BlockPageFieldConfig_Component_Config>>>;
};

export type BlockPageFieldConfig_Component_Config = TextFormField | BlocksFieldConfig;

export type TextFormField = {
  __typename?: 'TextFormField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
};

export type BlocksFieldConfig = {
  __typename?: 'BlocksFieldConfig';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  templates?: Maybe<BlocksTemplates>;
};

export type BlocksTemplates = {
  __typename?: 'BlocksTemplates';
  SidecarFieldConfig?: Maybe<SidecarFieldConfig>;
  ExcerptPostFieldConfig?: Maybe<ExcerptPostFieldConfig>;
  PostListFieldConfig?: Maybe<PostListFieldConfig>;
  PriceListFieldConfig?: Maybe<PriceListFieldConfig>;
  AuthorListFieldConfig?: Maybe<AuthorListFieldConfig>;
  SponsorListFieldConfig?: Maybe<SponsorListFieldConfig>;
  PageReferenceFieldConfig?: Maybe<PageReferenceFieldConfig>;
  SectionIndexFieldConfig?: Maybe<SectionIndexFieldConfig>;
};

export type SidecarFieldConfig = {
  __typename?: 'SidecarFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<SidecarFieldConfig_Component_Config>>>;
};

export type SidecarFieldConfig_Component_Config = TextFormField | ImageFormField | CtaFieldsListSidecarConfig | ActionsFieldConfig | SelectFormField;

export type ImageFormField = {
  __typename?: 'ImageFormField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<ImageWrapInner>>>;
};

export type ImageWrapInner = {
  __typename?: 'ImageWrapInner';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
};

export type CtaFieldsListSidecarConfig = {
  __typename?: 'CtaFieldsListSidecarConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<CtaFieldsListSidecarConfigFields>>>;
};

export type CtaFieldsListSidecarConfigFields = TextFormField;

export type ActionsFieldConfig = {
  __typename?: 'ActionsFieldConfig';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  templates?: Maybe<ActionsTemplates>;
};

export type ActionsTemplates = {
  __typename?: 'ActionsTemplates';
  ActionVideoFieldConfig?: Maybe<ActionVideoFieldConfig>;
  ActionNewsletterFieldConfig?: Maybe<ActionNewsletterFieldConfig>;
  ActionPageReferenceFieldConfig?: Maybe<ActionPageReferenceFieldConfig>;
};

export type ActionVideoFieldConfig = {
  __typename?: 'ActionVideoFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<ActionVideoFieldConfig_Component_Config>>>;
};

export type ActionVideoFieldConfig_Component_Config = TextFormField;

export type ActionNewsletterFieldConfig = {
  __typename?: 'ActionNewsletterFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<ActionNewsletterFieldConfig_Component_Config>>>;
};

export type ActionNewsletterFieldConfig_Component_Config = TextFormField;

export type ActionPageReferenceFieldConfig = {
  __typename?: 'ActionPageReferenceFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<ActionPageReferenceFieldConfig_Component_Config>>>;
};

export type ActionPageReferenceFieldConfig_Component_Config = SelectFormField | ButtonSettingsFieldsListActionPageReferenceConfig;

export type SelectFormField = {
  __typename?: 'SelectFormField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  options?: Maybe<Array<Maybe<Scalars['String']>>>;
};

export type ButtonSettingsFieldsListActionPageReferenceConfig = {
  __typename?: 'ButtonSettingsFieldsListActionPageReferenceConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<ButtonSettingsFieldsListActionPageReferenceConfigFields>>>;
};

export type ButtonSettingsFieldsListActionPageReferenceConfigFields = TextFormField;

export type ExcerptPostFieldConfig = {
  __typename?: 'ExcerptPostFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<ExcerptPostFieldConfig_Component_Config>>>;
};

export type ExcerptPostFieldConfig_Component_Config = SelectFormField | TextFormField;

export type PostListFieldConfig = {
  __typename?: 'PostListFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<PostListFieldConfig_Component_Config>>>;
};

export type PostListFieldConfig_Component_Config = PostsFieldsListPostListConfig;

export type PostsFieldsListPostListConfig = {
  __typename?: 'PostsFieldsListPostListConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<PostsFieldsListPostListConfigFields>>>;
};

export type PostsFieldsListPostListConfigFields = SelectFormField;

export type PriceListFieldConfig = {
  __typename?: 'PriceListFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<PriceListFieldConfig_Component_Config>>>;
};

export type PriceListFieldConfig_Component_Config = TextFormField | PricesFieldsListPriceListConfig;

export type PricesFieldsListPriceListConfig = {
  __typename?: 'PricesFieldsListPriceListConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<PricesFieldsListPriceListConfigFields>>>;
};

export type PricesFieldsListPriceListConfigFields = TextFormField | BulletPointsListPriceListPricesConfig | SelectFormField;

export type BulletPointsListPriceListPricesConfig = {
  __typename?: 'BulletPointsListPriceListPricesConfig';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  itemField?: Maybe<BulletPointsListPriceListPricesConfigItem>;
};

export type BulletPointsListPriceListPricesConfigItem = {
  __typename?: 'BulletPointsListPriceListPricesConfigItem';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
};

export type AuthorListFieldConfig = {
  __typename?: 'AuthorListFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<AuthorListFieldConfig_Component_Config>>>;
};

export type AuthorListFieldConfig_Component_Config = AuthorsListAuthorListConfig;

export type AuthorsListAuthorListConfig = {
  __typename?: 'AuthorsListAuthorListConfig';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<AuthorsListAuthorListConfigItem>>>;
};

export type AuthorsListAuthorListConfigItem = {
  __typename?: 'AuthorsListAuthorListConfigItem';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  options?: Maybe<Array<Maybe<Scalars['String']>>>;
};

export type SponsorListFieldConfig = {
  __typename?: 'SponsorListFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<SponsorListFieldConfig_Component_Config>>>;
};

export type SponsorListFieldConfig_Component_Config = TextFormField | SponsorFieldsListSponsorListConfig;

export type SponsorFieldsListSponsorListConfig = {
  __typename?: 'SponsorFieldsListSponsorListConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<SponsorFieldsListSponsorListConfigFields>>>;
};

export type SponsorFieldsListSponsorListConfigFields = TextFormField | ImageFormField;

export type PageReferenceFieldConfig = {
  __typename?: 'PageReferenceFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<PageReferenceFieldConfig_Component_Config>>>;
};

export type PageReferenceFieldConfig_Component_Config = TextFormField | SelectFormField;

export type SectionIndexFieldConfig = {
  __typename?: 'SectionIndexFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<SectionIndexFieldConfig_Component_Config>>>;
};

export type SectionIndexFieldConfig_Component_Config = TextFormField | SelectFormField;

export type BlockPageData = {
  __typename?: 'BlockPageData';
  _template?: Maybe<Scalars['String']>;
  title?: Maybe<Scalars['String']>;
  blocks?: Maybe<Array<Maybe<BlocksUnion>>>;
};

export type BlocksUnion = SidecarData | ExcerptPostData | PostListData | PriceListData | AuthorListData | SponsorListData | PageReferenceData | SectionIndexData;

export type SidecarData = {
  __typename?: 'SidecarData';
  _template?: Maybe<Scalars['String']>;
  text?: Maybe<Scalars['String']>;
  image?: Maybe<ImageGallerySidecar>;
  cta?: Maybe<CtaFieldsSidecar>;
  actions?: Maybe<Array<Maybe<ActionsUnion>>>;
  style?: Maybe<Scalars['String']>;
};

export type ImageGallerySidecar = {
  __typename?: 'ImageGallerySidecar';
  path: Scalars['String'];
  absolutePath?: Maybe<Scalars['String']>;
};

export type CtaFieldsSidecar = {
  __typename?: 'CtaFieldsSidecar';
  header?: Maybe<Scalars['String']>;
};

export type ActionsUnion = ActionVideoData | ActionNewsletterData | ActionPageReferenceData;

export type ActionVideoData = {
  __typename?: 'ActionVideoData';
  _template?: Maybe<Scalars['String']>;
  url?: Maybe<Scalars['String']>;
};

export type ActionNewsletterData = {
  __typename?: 'ActionNewsletterData';
  _template?: Maybe<Scalars['String']>;
  body?: Maybe<Scalars['String']>;
  footer?: Maybe<Scalars['String']>;
};

export type ActionPageReferenceData = {
  __typename?: 'ActionPageReferenceData';
  _template?: Maybe<Scalars['String']>;
  page?: Maybe<PageSelectActionPageReference>;
  button_settings?: Maybe<ButtonSettingsFieldsActionPageReference>;
};

export type PageSelectActionPageReference = BlockPage;

export type ButtonSettingsFieldsActionPageReference = {
  __typename?: 'ButtonSettingsFieldsActionPageReference';
  label?: Maybe<Scalars['String']>;
};

export type ExcerptPostData = {
  __typename?: 'ExcerptPostData';
  _template?: Maybe<Scalars['String']>;
  post?: Maybe<PostSelectExcerptPost>;
  description?: Maybe<Scalars['String']>;
  style?: Maybe<Scalars['String']>;
};

export type PostSelectExcerptPost = Post;

export type Post = {
  __typename?: 'Post';
  form?: Maybe<PostFieldConfig>;
  absolutePath?: Maybe<Scalars['String']>;
  path: Scalars['String'];
  content: Scalars['String'];
  excerpt?: Maybe<Scalars['String']>;
  data: PostData;
};

export type PostFieldConfig = {
  __typename?: 'PostFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<PostFieldConfig_Component_Config>>>;
};

export type PostFieldConfig_Component_Config = TextFormField | SelectFormField | ImageFormField | TagsFormField;

export type TagsFormField = {
  __typename?: 'TagsFormField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
};

export type PostData = {
  __typename?: 'PostData';
  _template?: Maybe<Scalars['String']>;
  title?: Maybe<Scalars['String']>;
  author?: Maybe<AuthorSelectPost>;
  image?: Maybe<ImageGalleryPost>;
  hashtags?: Maybe<Array<Maybe<Scalars['String']>>>;
};

export type AuthorSelectPost = Author;

export type Author = {
  __typename?: 'Author';
  form?: Maybe<AuthorFieldConfig>;
  absolutePath?: Maybe<Scalars['String']>;
  path: Scalars['String'];
  content: Scalars['String'];
  excerpt?: Maybe<Scalars['String']>;
  data: AuthorData;
};

export type AuthorFieldConfig = {
  __typename?: 'AuthorFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<AuthorFieldConfig_Component_Config>>>;
};

export type AuthorFieldConfig_Component_Config = TextFormField | ImageFormField | AnecdotesListAuthorConfig | AccoladesFieldsListAuthorConfig;

export type AnecdotesListAuthorConfig = {
  __typename?: 'AnecdotesListAuthorConfig';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  itemField?: Maybe<AnecdotesListAuthorConfigItem>;
};

export type AnecdotesListAuthorConfigItem = {
  __typename?: 'AnecdotesListAuthorConfigItem';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
};

export type AccoladesFieldsListAuthorConfig = {
  __typename?: 'AccoladesFieldsListAuthorConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<AccoladesFieldsListAuthorConfigFields>>>;
};

export type AccoladesFieldsListAuthorConfigFields = TextFormField;

export type AuthorData = {
  __typename?: 'AuthorData';
  _template?: Maybe<Scalars['String']>;
  name: Scalars['String'];
  image?: Maybe<ImageGalleryAuthor>;
  gallery?: Maybe<Array<Maybe<GalleryGalleryAuthor>>>;
  anecdotes?: Maybe<Array<Maybe<Scalars['String']>>>;
  accolades?: Maybe<Array<Maybe<AccoladesFieldsListAuthor>>>;
};

export type ImageGalleryAuthor = {
  __typename?: 'ImageGalleryAuthor';
  path: Scalars['String'];
  absolutePath?: Maybe<Scalars['String']>;
};

export type GalleryGalleryAuthor = {
  __typename?: 'GalleryGalleryAuthor';
  path: Scalars['String'];
  absolutePath?: Maybe<Scalars['String']>;
};

export type AccoladesFieldsListAuthor = {
  __typename?: 'AccoladesFieldsListAuthor';
  figure?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
};

export type ImageGalleryPost = {
  __typename?: 'ImageGalleryPost';
  path: Scalars['String'];
  absolutePath?: Maybe<Scalars['String']>;
};

export type PostListData = {
  __typename?: 'PostListData';
  _template?: Maybe<Scalars['String']>;
  posts?: Maybe<Array<Maybe<PostsFieldsListPostList>>>;
};

export type PostsFieldsListPostList = {
  __typename?: 'PostsFieldsListPostList';
  post?: Maybe<PostSelectPostListPosts>;
};

export type PostSelectPostListPosts = Post;

export type PriceListData = {
  __typename?: 'PriceListData';
  _template?: Maybe<Scalars['String']>;
  heading: Scalars['String'];
  prices?: Maybe<Array<Maybe<PricesFieldsListPriceList>>>;
};

export type PricesFieldsListPriceList = {
  __typename?: 'PricesFieldsListPriceList';
  title: Scalars['String'];
  description: Scalars['String'];
  bullet_points?: Maybe<Array<Maybe<Scalars['String']>>>;
  category?: Maybe<Scalars['String']>;
};

export type AuthorListData = {
  __typename?: 'AuthorListData';
  _template?: Maybe<Scalars['String']>;
  authors?: Maybe<Array<Maybe<AuthorsListAuthorList>>>;
};

export type AuthorsListAuthorList = Author;

export type SponsorListData = {
  __typename?: 'SponsorListData';
  _template?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  sponsor?: Maybe<Array<Maybe<SponsorFieldsListSponsorList>>>;
};

export type SponsorFieldsListSponsorList = {
  __typename?: 'SponsorFieldsListSponsorList';
  name?: Maybe<Scalars['String']>;
  url?: Maybe<Scalars['String']>;
  image?: Maybe<ImageGallerySponsorListSponsor>;
};

export type ImageGallerySponsorListSponsor = {
  __typename?: 'ImageGallerySponsorListSponsor';
  path: Scalars['String'];
  absolutePath?: Maybe<Scalars['String']>;
};

export type PageReferenceData = {
  __typename?: 'PageReferenceData';
  _template?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  page?: Maybe<PageSelectPageReference>;
};

export type PageSelectPageReference = BlockPage;

export type SectionIndexData = {
  __typename?: 'SectionIndexData';
  _template?: Maybe<Scalars['String']>;
  body?: Maybe<Scalars['String']>;
  limit?: Maybe<Scalars['Int']>;
  section?: Maybe<Scalars['String']>;
};

export type Menu = {
  __typename?: 'Menu';
  form?: Maybe<MenuFieldConfig>;
  absolutePath?: Maybe<Scalars['String']>;
  path: Scalars['String'];
  content: Scalars['String'];
  excerpt?: Maybe<Scalars['String']>;
  data: MenuData;
};

export type MenuFieldConfig = {
  __typename?: 'MenuFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<MenuFieldConfig_Component_Config>>>;
};

export type MenuFieldConfig_Component_Config = ImageFormField | MenuItemFieldsListMenuConfig;

export type MenuItemFieldsListMenuConfig = {
  __typename?: 'MenuItemFieldsListMenuConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<MenuItemFieldsListMenuConfigFields>>>;
};

export type MenuItemFieldsListMenuConfigFields = TextFormField | SelectFormField;

export type MenuData = {
  __typename?: 'MenuData';
  _template?: Maybe<Scalars['String']>;
  logo?: Maybe<LogoGalleryMenu>;
  menu_item?: Maybe<Array<Maybe<MenuItemFieldsListMenu>>>;
};

export type LogoGalleryMenu = {
  __typename?: 'LogoGalleryMenu';
  path: Scalars['String'];
  absolutePath?: Maybe<Scalars['String']>;
};

export type MenuItemFieldsListMenu = {
  __typename?: 'MenuItemFieldsListMenu';
  label?: Maybe<Scalars['String']>;
  page?: Maybe<PageSelectMenuMenuItem>;
};

export type PageSelectMenuMenuItem = BlockPage;

export type Mutation = {
  __typename?: 'Mutation';
  document?: Maybe<DocumentUnion>;
};


export type MutationDocumentArgs = {
  path: Scalars['String'];
  params?: Maybe<DocumentInput>;
};

export type DocumentInput = {
  BlockPageInput?: Maybe<BlockPageInput>;
  PostInput?: Maybe<PostInput>;
  AuthorInput?: Maybe<AuthorInput>;
  MenuInput?: Maybe<MenuInput>;
};

export type BlockPageInput = {
  data?: Maybe<BlockPageDataInput>;
  content?: Maybe<Scalars['String']>;
};

export type BlockPageDataInput = {
  title?: Maybe<Scalars['String']>;
  blocks?: Maybe<Array<Maybe<BlocksInput>>>;
};

export type BlocksInput = {
  SidecarInput?: Maybe<SidecarDataInput>;
  ExcerptPostInput?: Maybe<ExcerptPostDataInput>;
  PostListInput?: Maybe<PostListDataInput>;
  PriceListInput?: Maybe<PriceListDataInput>;
  AuthorListInput?: Maybe<AuthorListDataInput>;
  SponsorListInput?: Maybe<SponsorListDataInput>;
  PageReferenceInput?: Maybe<PageReferenceDataInput>;
  SectionIndexInput?: Maybe<SectionIndexDataInput>;
};

export type SidecarDataInput = {
  text?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
  cta?: Maybe<CtaFieldsSidecarInput>;
  actions?: Maybe<Array<Maybe<ActionsInput>>>;
  style?: Maybe<StyleSelectSidecar>;
};

export type CtaFieldsSidecarInput = {
  header?: Maybe<Scalars['String']>;
};

export type ActionsInput = {
  ActionVideoInput?: Maybe<ActionVideoDataInput>;
  ActionNewsletterInput?: Maybe<ActionNewsletterDataInput>;
  ActionPageReferenceInput?: Maybe<ActionPageReferenceDataInput>;
};

export type ActionVideoDataInput = {
  url?: Maybe<Scalars['String']>;
};

export type ActionNewsletterDataInput = {
  body?: Maybe<Scalars['String']>;
  footer?: Maybe<Scalars['String']>;
};

export type ActionPageReferenceDataInput = {
  page?: Maybe<Scalars['String']>;
  button_settings?: Maybe<ButtonSettingsFieldsActionPageReferenceInput>;
};

export type ButtonSettingsFieldsActionPageReferenceInput = {
  label?: Maybe<Scalars['String']>;
};

export enum StyleSelectSidecar {
  Sidecar = 'Sidecar',
  Column = 'Column',
  Slant = 'Slant'
}

export type ExcerptPostDataInput = {
  post?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  style?: Maybe<StyleSelectExcerptPost>;
};

export enum StyleSelectExcerptPost {
  Simple = 'Simple',
  Full = 'Full'
}

export type PostListDataInput = {
  posts?: Maybe<Array<Maybe<PostsFieldsListPostListInput>>>;
};

export type PostsFieldsListPostListInput = {
  post?: Maybe<Scalars['String']>;
};

export type PriceListDataInput = {
  heading?: Maybe<Scalars['String']>;
  prices?: Maybe<Array<Maybe<PricesFieldsListPriceListInput>>>;
};

export type PricesFieldsListPriceListInput = {
  title?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  bullet_points?: Maybe<Array<Maybe<Scalars['String']>>>;
  category?: Maybe<CategorySelectPriceListPrices>;
};

export enum CategorySelectPriceListPrices {
  Basic = 'Basic',
  Free = 'Free',
  Pro = 'Pro'
}

export type AuthorListDataInput = {
  authors?: Maybe<Array<Maybe<Scalars['String']>>>;
};

export type SponsorListDataInput = {
  description?: Maybe<Scalars['String']>;
  sponsor?: Maybe<Array<Maybe<SponsorFieldsListSponsorListInput>>>;
};

export type SponsorFieldsListSponsorListInput = {
  name?: Maybe<Scalars['String']>;
  url?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
};

export type PageReferenceDataInput = {
  description?: Maybe<Scalars['String']>;
  page?: Maybe<Scalars['String']>;
};

export type SectionIndexDataInput = {
  body?: Maybe<Scalars['String']>;
  limit?: Maybe<Scalars['Int']>;
  section?: Maybe<SectionSelectSectionIndex>;
};

export enum SectionSelectSectionIndex {
  Posts = 'posts',
  Pages = 'pages',
  Authors = 'authors'
}

export type PostInput = {
  data?: Maybe<PostDataInput>;
  content?: Maybe<Scalars['String']>;
};

export type PostDataInput = {
  title?: Maybe<Scalars['String']>;
  author?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
  hashtags?: Maybe<Array<Maybe<Scalars['String']>>>;
};

export type AuthorInput = {
  data?: Maybe<AuthorDataInput>;
  content?: Maybe<Scalars['String']>;
};

export type AuthorDataInput = {
  name?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
  gallery?: Maybe<Array<Maybe<Scalars['String']>>>;
  anecdotes?: Maybe<Array<Maybe<Scalars['String']>>>;
  accolades?: Maybe<Array<Maybe<AccoladesFieldsListAuthorInput>>>;
};

export type AccoladesFieldsListAuthorInput = {
  figure?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
};

export type MenuInput = {
  data?: Maybe<MenuDataInput>;
  content?: Maybe<Scalars['String']>;
};

export type MenuDataInput = {
  logo?: Maybe<Scalars['String']>;
  menu_item?: Maybe<Array<Maybe<MenuItemFieldsListMenuInput>>>;
};

export type MenuItemFieldsListMenuInput = {
  label?: Maybe<Scalars['String']>;
  page?: Maybe<Scalars['String']>;
};


