// DO NOT MODIFY THIS FILE. This file is automatically generated by Forestry
export type Maybe<T> = T | null;
export type Exact<T extends { [key: string]: any }> = { [K in keyof T]: T[K] };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
};

export type Query = {
  __typename?: 'Query';
  document?: Maybe<DocumentUnion>;
};


export type QueryDocumentArgs = {
  path: Scalars['String'];
};

export type DocumentUnion = BlockPage | Post | Author | Menu;

export type BlockPage = {
  __typename?: 'BlockPage';
  form?: Maybe<BlockPageFieldConfig>;
  absolutePath: Scalars['String'];
  path: Scalars['String'];
  content: Scalars['String'];
  excerpt?: Maybe<Scalars['String']>;
  data: BlockPageData;
};

export type BlockPageFieldConfig = {
  __typename?: 'BlockPageFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<BlockPageFieldConfig_Component_Config>>>;
};

export type BlockPageFieldConfig_Component_Config = TextFormField | BlocksFieldConfig;

export type TextFormField = {
  __typename?: 'TextFormField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  value?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
};

export type BlocksFieldConfig = {
  __typename?: 'BlocksFieldConfig';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  value?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  templates?: Maybe<BlocksTemplates>;
};

export type BlocksTemplates = {
  __typename?: 'BlocksTemplates';
  SidecarFieldConfig?: Maybe<SidecarFieldConfig>;
  ExcerptPostFieldConfig?: Maybe<ExcerptPostFieldConfig>;
  PostListFieldConfig?: Maybe<PostListFieldConfig>;
  PriceListFieldConfig?: Maybe<PriceListFieldConfig>;
  AuthorListFieldConfig?: Maybe<AuthorListFieldConfig>;
  SponsorListFieldConfig?: Maybe<SponsorListFieldConfig>;
  PageReferenceFieldConfig?: Maybe<PageReferenceFieldConfig>;
  SectionIndexFieldConfig?: Maybe<SectionIndexFieldConfig>;
};

export type SidecarFieldConfig = {
  __typename?: 'SidecarFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<SidecarFieldConfig_Component_Config>>>;
};

export type SidecarFieldConfig_Component_Config = TextFormField | ImageFormField | CtaFieldsListSidecarConfig | ActionsFieldConfig | SelectFormField;

export type ImageFormField = {
  __typename?: 'ImageFormField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  value?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
};

export type CtaFieldsListSidecarConfig = {
  __typename?: 'CtaFieldsListSidecarConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<CtaFieldsListSidecarConfig_Component_Config>>>;
};

export type CtaFieldsListSidecarConfig_Component_Config = TextFormField;

export type ActionsFieldConfig = {
  __typename?: 'ActionsFieldConfig';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  value?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  templates?: Maybe<ActionsTemplates>;
};

export type ActionsTemplates = {
  __typename?: 'ActionsTemplates';
  ActionVideoFieldConfig?: Maybe<ActionVideoFieldConfig>;
  ActionNewsletterFieldConfig?: Maybe<ActionNewsletterFieldConfig>;
  ActionPageReferenceFieldConfig?: Maybe<ActionPageReferenceFieldConfig>;
};

export type ActionVideoFieldConfig = {
  __typename?: 'ActionVideoFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<ActionVideoFieldConfig_Component_Config>>>;
};

export type ActionVideoFieldConfig_Component_Config = TextFormField;

export type ActionNewsletterFieldConfig = {
  __typename?: 'ActionNewsletterFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<ActionNewsletterFieldConfig_Component_Config>>>;
};

export type ActionNewsletterFieldConfig_Component_Config = TextFormField;

export type ActionPageReferenceFieldConfig = {
  __typename?: 'ActionPageReferenceFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<ActionPageReferenceFieldConfig_Component_Config>>>;
};

export type ActionPageReferenceFieldConfig_Component_Config = SelectFormField | ButtonSettingsFieldsListActionPageReferenceConfig;

export type SelectFormField = {
  __typename?: 'SelectFormField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  value?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  options?: Maybe<Array<Maybe<Scalars['String']>>>;
};

export type ButtonSettingsFieldsListActionPageReferenceConfig = {
  __typename?: 'ButtonSettingsFieldsListActionPageReferenceConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<ButtonSettingsFieldsListActionPageReferenceConfig_Component_Config>>>;
};

export type ButtonSettingsFieldsListActionPageReferenceConfig_Component_Config = TextFormField;

export type ExcerptPostFieldConfig = {
  __typename?: 'ExcerptPostFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<ExcerptPostFieldConfig_Component_Config>>>;
};

export type ExcerptPostFieldConfig_Component_Config = SelectFormField | TextFormField;

export type PostListFieldConfig = {
  __typename?: 'PostListFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<PostListFieldConfig_Component_Config>>>;
};

export type PostListFieldConfig_Component_Config = PostsFieldsListPostListConfig;

export type PostsFieldsListPostListConfig = {
  __typename?: 'PostsFieldsListPostListConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<PostsFieldsListPostListConfig_Component_Config>>>;
};

export type PostsFieldsListPostListConfig_Component_Config = SelectFormField;

export type PriceListFieldConfig = {
  __typename?: 'PriceListFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<PriceListFieldConfig_Component_Config>>>;
};

export type PriceListFieldConfig_Component_Config = TextFormField | PricesFieldsListPriceListConfig;

export type PricesFieldsListPriceListConfig = {
  __typename?: 'PricesFieldsListPriceListConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<PricesFieldsListPriceListConfig_Component_Config>>>;
};

export type PricesFieldsListPriceListConfig_Component_Config = TextFormField | BulletPointsListPriceListPricesConfig | SelectFormField;

export type BulletPointsListPriceListPricesConfig = {
  __typename?: 'BulletPointsListPriceListPricesConfig';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  value?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  itemField?: Maybe<BulletPointsListPriceListPricesConfigItem>;
};

export type BulletPointsListPriceListPricesConfigItem = {
  __typename?: 'BulletPointsListPriceListPricesConfigItem';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
};

export type AuthorListFieldConfig = {
  __typename?: 'AuthorListFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<AuthorListFieldConfig_Component_Config>>>;
};

export type AuthorListFieldConfig_Component_Config = AuthorsListAuthorListConfig;

export type AuthorsListAuthorListConfig = {
  __typename?: 'AuthorsListAuthorListConfig';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  value?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  itemField?: Maybe<AuthorsListAuthorListConfigItem>;
};

export type AuthorsListAuthorListConfigItem = {
  __typename?: 'AuthorsListAuthorListConfigItem';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  options?: Maybe<Array<Maybe<Scalars['String']>>>;
};

export type SponsorListFieldConfig = {
  __typename?: 'SponsorListFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<SponsorListFieldConfig_Component_Config>>>;
};

export type SponsorListFieldConfig_Component_Config = TextFormField | SponsorFieldsListSponsorListConfig;

export type SponsorFieldsListSponsorListConfig = {
  __typename?: 'SponsorFieldsListSponsorListConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<SponsorFieldsListSponsorListConfig_Component_Config>>>;
};

export type SponsorFieldsListSponsorListConfig_Component_Config = TextFormField | ImageFormField;

export type PageReferenceFieldConfig = {
  __typename?: 'PageReferenceFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<PageReferenceFieldConfig_Component_Config>>>;
};

export type PageReferenceFieldConfig_Component_Config = TextFormField | SelectFormField;

export type SectionIndexFieldConfig = {
  __typename?: 'SectionIndexFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<SectionIndexFieldConfig_Component_Config>>>;
};

export type SectionIndexFieldConfig_Component_Config = TextFormField | SelectFormField;

export type BlockPageData = {
  __typename?: 'BlockPageData';
  _template?: Maybe<Scalars['String']>;
  title?: Maybe<Scalars['String']>;
  blocks?: Maybe<Array<Maybe<BlocksUnion>>>;
};

export type BlocksUnion = SidecarData | ExcerptPostData | PostListData | PriceListData | AuthorListData | SponsorListData | PageReferenceData | SectionIndexData;

export type SidecarData = {
  __typename?: 'SidecarData';
  _template?: Maybe<Scalars['String']>;
  text?: Maybe<Scalars['String']>;
  image?: Maybe<ImageGallerySidecar>;
  cta?: Maybe<CtaFieldsSidecar>;
  actions?: Maybe<Array<Maybe<ActionsUnion>>>;
  style?: Maybe<Scalars['String']>;
};

export type ImageGallerySidecar = {
  __typename?: 'ImageGallerySidecar';
  path: Scalars['String'];
  absolutePath: Scalars['String'];
};

export type CtaFieldsSidecar = {
  __typename?: 'CtaFieldsSidecar';
  header?: Maybe<Scalars['String']>;
};

export type ActionsUnion = ActionVideoData | ActionNewsletterData | ActionPageReferenceData;

export type ActionVideoData = {
  __typename?: 'ActionVideoData';
  _template?: Maybe<Scalars['String']>;
  url?: Maybe<Scalars['String']>;
};

export type ActionNewsletterData = {
  __typename?: 'ActionNewsletterData';
  _template?: Maybe<Scalars['String']>;
  body?: Maybe<Scalars['String']>;
  footer?: Maybe<Scalars['String']>;
};

export type ActionPageReferenceData = {
  __typename?: 'ActionPageReferenceData';
  _template?: Maybe<Scalars['String']>;
  page?: Maybe<PageSelectActionPageReference>;
  button_settings?: Maybe<ButtonSettingsFieldsActionPageReference>;
};

export type PageSelectActionPageReference = BlockPage;

export type ButtonSettingsFieldsActionPageReference = {
  __typename?: 'ButtonSettingsFieldsActionPageReference';
  label?: Maybe<Scalars['String']>;
};

export type ExcerptPostData = {
  __typename?: 'ExcerptPostData';
  _template?: Maybe<Scalars['String']>;
  post?: Maybe<PostSelectExcerptPost>;
  description?: Maybe<Scalars['String']>;
  style?: Maybe<Scalars['String']>;
};

export type PostSelectExcerptPost = Post;

export type Post = {
  __typename?: 'Post';
  form?: Maybe<PostFieldConfig>;
  absolutePath: Scalars['String'];
  path: Scalars['String'];
  content: Scalars['String'];
  excerpt?: Maybe<Scalars['String']>;
  data: PostData;
};

export type PostFieldConfig = {
  __typename?: 'PostFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<PostFieldConfig_Component_Config>>>;
};

export type PostFieldConfig_Component_Config = TextFormField | SelectFormField | ImageFormField | TagsFormField;

export type TagsFormField = {
  __typename?: 'TagsFormField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  value?: Maybe<Array<Maybe<Scalars['String']>>>;
  description?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
};

export type PostData = {
  __typename?: 'PostData';
  _template?: Maybe<Scalars['String']>;
  title?: Maybe<Scalars['String']>;
  author?: Maybe<AuthorSelectPost>;
  image?: Maybe<ImageGalleryPost>;
  hashtags?: Maybe<Array<Maybe<Scalars['String']>>>;
};

export type AuthorSelectPost = Author;

export type Author = {
  __typename?: 'Author';
  form?: Maybe<AuthorFieldConfig>;
  absolutePath: Scalars['String'];
  path: Scalars['String'];
  content: Scalars['String'];
  excerpt?: Maybe<Scalars['String']>;
  data: AuthorData;
};

export type AuthorFieldConfig = {
  __typename?: 'AuthorFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<AuthorFieldConfig_Component_Config>>>;
};

export type AuthorFieldConfig_Component_Config = TextFormField | ImageFormField | AnecdotesListAuthorConfig | AccoladesFieldsListAuthorConfig;

export type AnecdotesListAuthorConfig = {
  __typename?: 'AnecdotesListAuthorConfig';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  value?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  itemField?: Maybe<AnecdotesListAuthorConfigItem>;
};

export type AnecdotesListAuthorConfigItem = {
  __typename?: 'AnecdotesListAuthorConfigItem';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
};

export type AccoladesFieldsListAuthorConfig = {
  __typename?: 'AccoladesFieldsListAuthorConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<AccoladesFieldsListAuthorConfig_Component_Config>>>;
};

export type AccoladesFieldsListAuthorConfig_Component_Config = TextFormField;

export type AuthorData = {
  __typename?: 'AuthorData';
  _template?: Maybe<Scalars['String']>;
  name: Scalars['String'];
  image?: Maybe<ImageGalleryAuthor>;
  gallery?: Maybe<Array<Maybe<GalleryGalleryAuthor>>>;
  anecdotes?: Maybe<Array<Maybe<Scalars['String']>>>;
  accolades?: Maybe<Array<Maybe<AccoladesFieldsListAuthor>>>;
};

export type ImageGalleryAuthor = {
  __typename?: 'ImageGalleryAuthor';
  path: Scalars['String'];
  absolutePath: Scalars['String'];
};

export type GalleryGalleryAuthor = {
  __typename?: 'GalleryGalleryAuthor';
  path: Scalars['String'];
  absolutePath: Scalars['String'];
};

export type AccoladesFieldsListAuthor = {
  __typename?: 'AccoladesFieldsListAuthor';
  figure?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
};

export type ImageGalleryPost = {
  __typename?: 'ImageGalleryPost';
  path: Scalars['String'];
  absolutePath: Scalars['String'];
};

export type PostListData = {
  __typename?: 'PostListData';
  _template?: Maybe<Scalars['String']>;
  posts?: Maybe<Array<Maybe<PostsFieldsListPostList>>>;
};

export type PostsFieldsListPostList = {
  __typename?: 'PostsFieldsListPostList';
  post?: Maybe<PostSelectPostListPosts>;
};

export type PostSelectPostListPosts = Post;

export type PriceListData = {
  __typename?: 'PriceListData';
  _template?: Maybe<Scalars['String']>;
  heading: Scalars['String'];
  prices?: Maybe<Array<Maybe<PricesFieldsListPriceList>>>;
};

export type PricesFieldsListPriceList = {
  __typename?: 'PricesFieldsListPriceList';
  title: Scalars['String'];
  description: Scalars['String'];
  bullet_points?: Maybe<Array<Maybe<Scalars['String']>>>;
  category?: Maybe<Scalars['String']>;
};

export type AuthorListData = {
  __typename?: 'AuthorListData';
  _template?: Maybe<Scalars['String']>;
  authors?: Maybe<Array<Maybe<AuthorsListAuthorList>>>;
};

export type AuthorsListAuthorList = Author;

export type SponsorListData = {
  __typename?: 'SponsorListData';
  _template?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  sponsor?: Maybe<Array<Maybe<SponsorFieldsListSponsorList>>>;
};

export type SponsorFieldsListSponsorList = {
  __typename?: 'SponsorFieldsListSponsorList';
  name?: Maybe<Scalars['String']>;
  url?: Maybe<Scalars['String']>;
  image?: Maybe<ImageGallerySponsorListSponsor>;
};

export type ImageGallerySponsorListSponsor = {
  __typename?: 'ImageGallerySponsorListSponsor';
  path: Scalars['String'];
  absolutePath: Scalars['String'];
};

export type PageReferenceData = {
  __typename?: 'PageReferenceData';
  _template?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  page?: Maybe<PageSelectPageReference>;
};

export type PageSelectPageReference = BlockPage;

export type SectionIndexData = {
  __typename?: 'SectionIndexData';
  _template?: Maybe<Scalars['String']>;
  body?: Maybe<Scalars['String']>;
  limit?: Maybe<Scalars['Int']>;
  section?: Maybe<Array<Maybe<SectionSelectSectionIndex>>>;
};

export type SectionSelectSectionIndex = ActionNewsletter | ActionPageReference | ActionVideo | AuthorList | Author | BlockPage | ExcerptPost | Menu | PageReference | PostList | Post | PriceList | SectionIndex | Sidecar | SponsorList;

export type ActionNewsletter = {
  __typename?: 'ActionNewsletter';
  form?: Maybe<ActionNewsletterFieldConfig>;
  absolutePath: Scalars['String'];
  path: Scalars['String'];
  content: Scalars['String'];
  excerpt?: Maybe<Scalars['String']>;
  data: ActionNewsletterData;
};

export type ActionPageReference = {
  __typename?: 'ActionPageReference';
  form?: Maybe<ActionPageReferenceFieldConfig>;
  absolutePath: Scalars['String'];
  path: Scalars['String'];
  content: Scalars['String'];
  excerpt?: Maybe<Scalars['String']>;
  data: ActionPageReferenceData;
};

export type ActionVideo = {
  __typename?: 'ActionVideo';
  form?: Maybe<ActionVideoFieldConfig>;
  absolutePath: Scalars['String'];
  path: Scalars['String'];
  content: Scalars['String'];
  excerpt?: Maybe<Scalars['String']>;
  data: ActionVideoData;
};

export type AuthorList = {
  __typename?: 'AuthorList';
  form?: Maybe<AuthorListFieldConfig>;
  absolutePath: Scalars['String'];
  path: Scalars['String'];
  content: Scalars['String'];
  excerpt?: Maybe<Scalars['String']>;
  data: AuthorListData;
};

export type ExcerptPost = {
  __typename?: 'ExcerptPost';
  form?: Maybe<ExcerptPostFieldConfig>;
  absolutePath: Scalars['String'];
  path: Scalars['String'];
  content: Scalars['String'];
  excerpt?: Maybe<Scalars['String']>;
  data: ExcerptPostData;
};

export type Menu = {
  __typename?: 'Menu';
  form?: Maybe<MenuFieldConfig>;
  absolutePath: Scalars['String'];
  path: Scalars['String'];
  content: Scalars['String'];
  excerpt?: Maybe<Scalars['String']>;
  data: MenuData;
};

export type MenuFieldConfig = {
  __typename?: 'MenuFieldConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<MenuFieldConfig_Component_Config>>>;
};

export type MenuFieldConfig_Component_Config = ImageFormField | MenuItemFieldsListMenuConfig;

export type MenuItemFieldsListMenuConfig = {
  __typename?: 'MenuItemFieldsListMenuConfig';
  label?: Maybe<Scalars['String']>;
  key?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<MenuItemFieldsListMenuConfig_Component_Config>>>;
};

export type MenuItemFieldsListMenuConfig_Component_Config = TextFormField | SelectFormField;

export type MenuData = {
  __typename?: 'MenuData';
  _template?: Maybe<Scalars['String']>;
  logo?: Maybe<LogoGalleryMenu>;
  menu_item?: Maybe<Array<Maybe<MenuItemFieldsListMenu>>>;
};

export type LogoGalleryMenu = {
  __typename?: 'LogoGalleryMenu';
  path: Scalars['String'];
  absolutePath: Scalars['String'];
};

export type MenuItemFieldsListMenu = {
  __typename?: 'MenuItemFieldsListMenu';
  label?: Maybe<Scalars['String']>;
  page?: Maybe<PageSelectMenuMenuItem>;
};

export type PageSelectMenuMenuItem = BlockPage;

export type PageReference = {
  __typename?: 'PageReference';
  form?: Maybe<PageReferenceFieldConfig>;
  absolutePath: Scalars['String'];
  path: Scalars['String'];
  content: Scalars['String'];
  excerpt?: Maybe<Scalars['String']>;
  data: PageReferenceData;
};

export type PostList = {
  __typename?: 'PostList';
  form?: Maybe<PostListFieldConfig>;
  absolutePath: Scalars['String'];
  path: Scalars['String'];
  content: Scalars['String'];
  excerpt?: Maybe<Scalars['String']>;
  data: PostListData;
};

export type PriceList = {
  __typename?: 'PriceList';
  form?: Maybe<PriceListFieldConfig>;
  absolutePath: Scalars['String'];
  path: Scalars['String'];
  content: Scalars['String'];
  excerpt?: Maybe<Scalars['String']>;
  data: PriceListData;
};

export type SectionIndex = {
  __typename?: 'SectionIndex';
  form?: Maybe<SectionIndexFieldConfig>;
  absolutePath: Scalars['String'];
  path: Scalars['String'];
  content: Scalars['String'];
  excerpt?: Maybe<Scalars['String']>;
  data: SectionIndexData;
};

export type Sidecar = {
  __typename?: 'Sidecar';
  form?: Maybe<SidecarFieldConfig>;
  absolutePath: Scalars['String'];
  path: Scalars['String'];
  content: Scalars['String'];
  excerpt?: Maybe<Scalars['String']>;
  data: SidecarData;
};

export type SponsorList = {
  __typename?: 'SponsorList';
  form?: Maybe<SponsorListFieldConfig>;
  absolutePath: Scalars['String'];
  path: Scalars['String'];
  content: Scalars['String'];
  excerpt?: Maybe<Scalars['String']>;
  data: SponsorListData;
};

export type Mutation = {
  __typename?: 'Mutation';
  document?: Maybe<DocumentUnion>;
};


export type MutationDocumentArgs = {
  path: Scalars['String'];
  params?: Maybe<DocumentInput>;
};

export type DocumentInput = {
  BlockPageInput?: Maybe<BlockPageInput>;
  PostInput?: Maybe<PostInput>;
  AuthorInput?: Maybe<AuthorInput>;
  MenuInput?: Maybe<MenuInput>;
};

export type BlockPageInput = {
  title?: Maybe<Scalars['String']>;
  blocks?: Maybe<Array<Maybe<BlocksInput>>>;
};

export type BlocksInput = {
  Sidecar_input?: Maybe<SidecarInput>;
  ExcerptPost_input?: Maybe<ExcerptPostInput>;
  PostList_input?: Maybe<PostListInput>;
  PriceList_input?: Maybe<PriceListInput>;
  AuthorList_input?: Maybe<AuthorListInput>;
  SponsorList_input?: Maybe<SponsorListInput>;
  PageReference_input?: Maybe<PageReferenceInput>;
  SectionIndex_input?: Maybe<SectionIndexInput>;
};

export type SidecarInput = {
  text?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
  cta?: Maybe<CtaFieldsSidecarInput>;
  actions?: Maybe<Array<Maybe<ActionsInput>>>;
  style?: Maybe<StyleSelectSidecar>;
};

export type CtaFieldsSidecarInput = {
  header?: Maybe<Scalars['String']>;
};

export type ActionsInput = {
  ActionVideo_input?: Maybe<ActionVideoInput>;
  ActionNewsletter_input?: Maybe<ActionNewsletterInput>;
  ActionPageReference_input?: Maybe<ActionPageReferenceInput>;
};

export type ActionVideoInput = {
  url?: Maybe<Scalars['String']>;
};

export type ActionNewsletterInput = {
  body?: Maybe<Scalars['String']>;
  footer?: Maybe<Scalars['String']>;
};

export type ActionPageReferenceInput = {
  page?: Maybe<Scalars['String']>;
  button_settings?: Maybe<ButtonSettingsFieldsActionPageReferenceInput>;
};

export type ButtonSettingsFieldsActionPageReferenceInput = {
  label?: Maybe<Scalars['String']>;
};

export enum StyleSelectSidecar {
  Sidecar = 'Sidecar',
  Column = 'Column',
  Slant = 'Slant'
}

export type ExcerptPostInput = {
  post?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  style?: Maybe<StyleSelectExcerptPost>;
};

export enum StyleSelectExcerptPost {
  Simple = 'Simple',
  Full = 'Full'
}

export type PostListInput = {
  posts?: Maybe<Array<Maybe<PostsFieldsListPostListInput>>>;
};

export type PostsFieldsListPostListInput = {
  post?: Maybe<Scalars['String']>;
};

export type PriceListInput = {
  heading?: Maybe<Scalars['String']>;
  prices?: Maybe<Array<Maybe<PricesFieldsListPriceListInput>>>;
};

export type PricesFieldsListPriceListInput = {
  title?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  bullet_points?: Maybe<Array<Maybe<Scalars['String']>>>;
  category?: Maybe<CategorySelectPriceListPrices>;
};

export enum CategorySelectPriceListPrices {
  Basic = 'Basic',
  Free = 'Free',
  Pro = 'Pro'
}

export type AuthorListInput = {
  authors?: Maybe<Array<Maybe<Scalars['String']>>>;
};

export type SponsorListInput = {
  description?: Maybe<Scalars['String']>;
  sponsor?: Maybe<Array<Maybe<SponsorFieldsListSponsorListInput>>>;
};

export type SponsorFieldsListSponsorListInput = {
  name?: Maybe<Scalars['String']>;
  url?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
};

export type PageReferenceInput = {
  description?: Maybe<Scalars['String']>;
  page?: Maybe<Scalars['String']>;
};

export type SectionIndexInput = {
  body?: Maybe<Scalars['String']>;
  limit?: Maybe<Scalars['Int']>;
  section?: Maybe<Scalars['String']>;
};

export type PostInput = {
  title?: Maybe<Scalars['String']>;
  author?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
  hashtags?: Maybe<Array<Maybe<Scalars['String']>>>;
};

export type AuthorInput = {
  name?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
  gallery?: Maybe<Array<Maybe<Scalars['String']>>>;
  anecdotes?: Maybe<Array<Maybe<Scalars['String']>>>;
  accolades?: Maybe<Array<Maybe<AccoladesFieldsListAuthorInput>>>;
};

export type AccoladesFieldsListAuthorInput = {
  figure?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
};

export type MenuInput = {
  logo?: Maybe<Scalars['String']>;
  menu_item?: Maybe<Array<Maybe<MenuItemFieldsListMenuInput>>>;
};

export type MenuItemFieldsListMenuInput = {
  label?: Maybe<Scalars['String']>;
  page?: Maybe<Scalars['String']>;
};

export type DocumentQueryQueryVariables = Exact<{
  path: Scalars['String'];
}>;


export type DocumentQueryQuery = (
  { __typename?: 'Query' }
  & { document?: Maybe<(
    { __typename: 'BlockPage' }
    & { form?: Maybe<(
      { __typename?: 'BlockPageFieldConfig' }
      & { fields?: Maybe<Array<Maybe<(
        { __typename?: 'TextFormField' }
        & Pick<TextFormField, 'name' | 'label' | 'component'>
      ) | (
        { __typename?: 'BlocksFieldConfig' }
        & Pick<BlocksFieldConfig, 'name' | 'label' | 'component'>
        & { templates?: Maybe<(
          { __typename?: 'BlocksTemplates' }
          & { AuthorListFieldConfig?: Maybe<(
            { __typename?: 'AuthorListFieldConfig' }
            & Pick<AuthorListFieldConfig, 'label' | 'key'>
            & { fields?: Maybe<Array<Maybe<(
              { __typename?: 'AuthorsListAuthorListConfig' }
              & Pick<AuthorsListAuthorListConfig, 'name' | 'label' | 'component'>
              & { itemField?: Maybe<(
                { __typename?: 'AuthorsListAuthorListConfigItem' }
                & Pick<AuthorsListAuthorListConfigItem, 'name' | 'label' | 'component' | 'options'>
              )> }
            )>>> }
          )>, SponsorListFieldConfig?: Maybe<(
            { __typename?: 'SponsorListFieldConfig' }
            & Pick<SponsorListFieldConfig, 'name' | 'label' | 'component'>
            & { fields?: Maybe<Array<Maybe<(
              { __typename?: 'TextFormField' }
              & Pick<TextFormField, 'name' | 'label' | 'value' | 'component'>
            ) | (
              { __typename?: 'SponsorFieldsListSponsorListConfig' }
              & Pick<SponsorFieldsListSponsorListConfig, 'label' | 'key' | 'name' | 'component'>
              & { fields?: Maybe<Array<Maybe<(
                { __typename?: 'TextFormField' }
                & Pick<TextFormField, 'name' | 'label' | 'component'>
              ) | (
                { __typename?: 'ImageFormField' }
                & Pick<ImageFormField, 'name' | 'label' | 'component'>
              )>>> }
            )>>> }
          )>, PageReferenceFieldConfig?: Maybe<(
            { __typename?: 'PageReferenceFieldConfig' }
            & Pick<PageReferenceFieldConfig, 'label' | 'key' | 'name'>
            & { fields?: Maybe<Array<Maybe<(
              { __typename?: 'TextFormField' }
              & Pick<TextFormField, 'name' | 'label' | 'value' | 'component'>
            ) | (
              { __typename?: 'SelectFormField' }
              & Pick<SelectFormField, 'name' | 'label' | 'value' | 'component' | 'options'>
            )>>> }
          )>, SidecarFieldConfig?: Maybe<(
            { __typename?: 'SidecarFieldConfig' }
            & Pick<SidecarFieldConfig, 'label' | 'key'>
            & { fields?: Maybe<Array<Maybe<(
              { __typename?: 'TextFormField' }
              & Pick<TextFormField, 'name' | 'label' | 'component'>
            ) | (
              { __typename?: 'ImageFormField' }
              & Pick<ImageFormField, 'name' | 'label' | 'component'>
            ) | (
              { __typename?: 'CtaFieldsListSidecarConfig' }
              & Pick<CtaFieldsListSidecarConfig, 'label' | 'key' | 'component'>
              & { fields?: Maybe<Array<Maybe<(
                { __typename?: 'TextFormField' }
                & Pick<TextFormField, 'name' | 'label' | 'component'>
              )>>> }
            ) | (
              { __typename?: 'ActionsFieldConfig' }
              & Pick<ActionsFieldConfig, 'name' | 'label' | 'component'>
              & { templates?: Maybe<(
                { __typename?: 'ActionsTemplates' }
                & { ActionVideoFieldConfig?: Maybe<(
                  { __typename?: 'ActionVideoFieldConfig' }
                  & Pick<ActionVideoFieldConfig, 'label' | 'key' | 'component'>
                  & { fields?: Maybe<Array<Maybe<(
                    { __typename?: 'TextFormField' }
                    & Pick<TextFormField, 'label' | 'name' | 'component'>
                  )>>> }
                )>, ActionNewsletterFieldConfig?: Maybe<(
                  { __typename?: 'ActionNewsletterFieldConfig' }
                  & Pick<ActionNewsletterFieldConfig, 'label' | 'key' | 'component'>
                  & { fields?: Maybe<Array<Maybe<(
                    { __typename?: 'TextFormField' }
                    & Pick<TextFormField, 'label' | 'name' | 'component'>
                  )>>> }
                )>, ActionPageReferenceFieldConfig?: Maybe<(
                  { __typename?: 'ActionPageReferenceFieldConfig' }
                  & Pick<ActionPageReferenceFieldConfig, 'label' | 'key' | 'component'>
                  & { fields?: Maybe<Array<Maybe<(
                    { __typename?: 'SelectFormField' }
                    & Pick<SelectFormField, 'name' | 'label' | 'component' | 'options'>
                  ) | (
                    { __typename?: 'ButtonSettingsFieldsListActionPageReferenceConfig' }
                    & Pick<ButtonSettingsFieldsListActionPageReferenceConfig, 'label' | 'key' | 'component'>
                    & { fields?: Maybe<Array<Maybe<(
                      { __typename?: 'TextFormField' }
                      & Pick<TextFormField, 'name' | 'label' | 'component'>
                    )>>> }
                  )>>> }
                )> }
              )> }
            ) | (
              { __typename?: 'SelectFormField' }
              & Pick<SelectFormField, 'name' | 'label' | 'component' | 'options'>
            )>>> }
          )>, SectionIndexFieldConfig?: Maybe<(
            { __typename?: 'SectionIndexFieldConfig' }
            & Pick<SectionIndexFieldConfig, 'label' | 'key'>
            & { fields?: Maybe<Array<Maybe<(
              { __typename?: 'TextFormField' }
              & Pick<TextFormField, 'name' | 'label' | 'component'>
            ) | (
              { __typename?: 'SelectFormField' }
              & Pick<SelectFormField, 'name' | 'label' | 'component' | 'options'>
            )>>> }
          )>, PriceListFieldConfig?: Maybe<(
            { __typename?: 'PriceListFieldConfig' }
            & Pick<PriceListFieldConfig, 'label' | 'key'>
            & { fields?: Maybe<Array<Maybe<(
              { __typename?: 'TextFormField' }
              & Pick<TextFormField, 'name' | 'label' | 'component'>
            ) | (
              { __typename?: 'PricesFieldsListPriceListConfig' }
              & Pick<PricesFieldsListPriceListConfig, 'label' | 'key' | 'component' | 'name'>
              & { fields?: Maybe<Array<Maybe<(
                { __typename?: 'TextFormField' }
                & Pick<TextFormField, 'name' | 'label' | 'component'>
              ) | (
                { __typename?: 'BulletPointsListPriceListPricesConfig' }
                & Pick<BulletPointsListPriceListPricesConfig, 'name' | 'label' | 'component'>
                & { itemField?: Maybe<(
                  { __typename?: 'BulletPointsListPriceListPricesConfigItem' }
                  & Pick<BulletPointsListPriceListPricesConfigItem, 'name' | 'label' | 'component'>
                )> }
              ) | (
                { __typename?: 'SelectFormField' }
                & Pick<SelectFormField, 'name' | 'label' | 'options' | 'component'>
              )>>> }
            )>>> }
          )> }
        )> }
      )>>> }
    )>, data: (
      { __typename: 'BlockPageData' }
      & Pick<BlockPageData, '_template' | 'title'>
      & { blocks?: Maybe<Array<Maybe<(
        { __typename: 'SidecarData' }
        & Pick<SidecarData, '_template' | 'style' | 'text'>
        & { image?: Maybe<(
          { __typename?: 'ImageGallerySidecar' }
          & Pick<ImageGallerySidecar, 'path' | 'absolutePath'>
        )>, cta?: Maybe<(
          { __typename?: 'CtaFieldsSidecar' }
          & Pick<CtaFieldsSidecar, 'header'>
        )>, actions?: Maybe<Array<Maybe<(
          { __typename?: 'ActionVideoData' }
          & Pick<ActionVideoData, '_template' | 'url'>
        ) | (
          { __typename?: 'ActionNewsletterData' }
          & Pick<ActionNewsletterData, '_template' | 'body' | 'footer'>
        ) | (
          { __typename?: 'ActionPageReferenceData' }
          & Pick<ActionPageReferenceData, '_template'>
          & { page?: Maybe<(
            { __typename?: 'BlockPage' }
            & Pick<BlockPage, 'path'>
          )>, button_settings?: Maybe<(
            { __typename?: 'ButtonSettingsFieldsActionPageReference' }
            & Pick<ButtonSettingsFieldsActionPageReference, 'label'>
          )> }
        )>>> }
      ) | (
        { __typename: 'ExcerptPostData' }
        & Pick<ExcerptPostData, '_template' | 'style' | 'description'>
        & { post?: Maybe<(
          { __typename: 'Post' }
          & Pick<Post, 'path' | 'excerpt'>
          & { data: (
            { __typename?: 'PostData' }
            & Pick<PostData, 'title'>
            & { image?: Maybe<(
              { __typename?: 'ImageGalleryPost' }
              & Pick<ImageGalleryPost, 'path' | 'absolutePath'>
            )>, author?: Maybe<(
              { __typename?: 'Author' }
              & { data: (
                { __typename?: 'AuthorData' }
                & Pick<AuthorData, 'name'>
                & { image?: Maybe<(
                  { __typename?: 'ImageGalleryAuthor' }
                  & Pick<ImageGalleryAuthor, 'path' | 'absolutePath'>
                )> }
              ) }
            )> }
          ) }
        )> }
      ) | { __typename: 'PostListData' } | (
        { __typename: 'PriceListData' }
        & Pick<PriceListData, '_template' | 'heading'>
        & { prices?: Maybe<Array<Maybe<(
          { __typename?: 'PricesFieldsListPriceList' }
          & Pick<PricesFieldsListPriceList, 'title' | 'description' | 'bullet_points' | 'category'>
        )>>> }
      ) | (
        { __typename: 'AuthorListData' }
        & Pick<AuthorListData, '_template'>
        & { authors?: Maybe<Array<Maybe<(
          { __typename: 'Author' }
          & Pick<Author, 'path' | 'content' | 'excerpt'>
          & { data: (
            { __typename?: 'AuthorData' }
            & Pick<AuthorData, 'name' | 'anecdotes'>
            & { image?: Maybe<(
              { __typename?: 'ImageGalleryAuthor' }
              & Pick<ImageGalleryAuthor, 'path' | 'absolutePath'>
            )>, gallery?: Maybe<Array<Maybe<(
              { __typename?: 'GalleryGalleryAuthor' }
              & Pick<GalleryGalleryAuthor, 'path' | 'absolutePath'>
            )>>>, accolades?: Maybe<Array<Maybe<(
              { __typename?: 'AccoladesFieldsListAuthor' }
              & Pick<AccoladesFieldsListAuthor, 'figure' | 'description'>
            )>>> }
          ) }
        )>>> }
      ) | (
        { __typename: 'SponsorListData' }
        & Pick<SponsorListData, '_template' | 'description'>
        & { sponsor?: Maybe<Array<Maybe<(
          { __typename?: 'SponsorFieldsListSponsorList' }
          & Pick<SponsorFieldsListSponsorList, 'name' | 'url'>
          & { image?: Maybe<(
            { __typename?: 'ImageGallerySponsorListSponsor' }
            & Pick<ImageGallerySponsorListSponsor, 'path' | 'absolutePath'>
          )> }
        )>>> }
      ) | (
        { __typename: 'PageReferenceData' }
        & Pick<PageReferenceData, '_template' | 'description'>
        & { page?: Maybe<(
          { __typename: 'BlockPage' }
          & Pick<BlockPage, 'path'>
        )> }
      ) | (
        { __typename: 'SectionIndexData' }
        & Pick<SectionIndexData, '_template' | 'body' | 'limit'>
        & { section?: Maybe<Array<Maybe<{ __typename: 'ActionNewsletter' } | { __typename: 'ActionPageReference' } | { __typename: 'ActionVideo' } | { __typename: 'AuthorList' } | { __typename: 'Author' } | { __typename: 'BlockPage' } | { __typename: 'ExcerptPost' } | { __typename: 'Menu' } | { __typename: 'PageReference' } | { __typename: 'PostList' } | (
          { __typename: 'Post' }
          & Pick<Post, 'path' | 'excerpt'>
          & { data: (
            { __typename?: 'PostData' }
            & Pick<PostData, 'hashtags' | 'title'>
            & { image?: Maybe<(
              { __typename?: 'ImageGalleryPost' }
              & Pick<ImageGalleryPost, 'path' | 'absolutePath'>
            )>, author?: Maybe<(
              { __typename: 'Author' }
              & Pick<Author, 'path' | 'content' | 'excerpt'>
              & { data: (
                { __typename?: 'AuthorData' }
                & Pick<AuthorData, 'name'>
                & { image?: Maybe<(
                  { __typename?: 'ImageGalleryAuthor' }
                  & Pick<ImageGalleryAuthor, 'path' | 'absolutePath'>
                )>, gallery?: Maybe<Array<Maybe<(
                  { __typename?: 'GalleryGalleryAuthor' }
                  & Pick<GalleryGalleryAuthor, 'path' | 'absolutePath'>
                )>>> }
              ) }
            )> }
          ) }
        ) | { __typename: 'PriceList' } | { __typename: 'SectionIndex' } | { __typename: 'Sidecar' } | { __typename: 'SponsorList' }>>> }
      )>>> }
    ) }
  ) | (
    { __typename: 'Post' }
    & Pick<Post, 'path' | 'content' | 'excerpt'>
    & { form?: Maybe<(
      { __typename?: 'PostFieldConfig' }
      & { fields?: Maybe<Array<Maybe<{ __typename?: 'TextFormField' } | (
        { __typename?: 'SelectFormField' }
        & Pick<SelectFormField, 'name' | 'options'>
      ) | { __typename?: 'ImageFormField' } | { __typename?: 'TagsFormField' }>>> }
    )>, data: (
      { __typename?: 'PostData' }
      & Pick<PostData, 'title' | 'hashtags'>
      & { image?: Maybe<(
        { __typename?: 'ImageGalleryPost' }
        & Pick<ImageGalleryPost, 'path' | 'absolutePath'>
      )>, author?: Maybe<(
        { __typename?: 'Author' }
        & Pick<Author, 'path'>
        & { data: (
          { __typename?: 'AuthorData' }
          & Pick<AuthorData, 'name'>
          & { image?: Maybe<(
            { __typename?: 'ImageGalleryAuthor' }
            & Pick<ImageGalleryAuthor, 'path' | 'absolutePath'>
          )> }
        ) }
      )> }
    ) }
  ) | { __typename: 'Author' } | { __typename: 'Menu' }> }
);

    