---
label: Author
name: author
fields:
  - name: name
    type: text
    label: Name
  - name: isAuthor
    type: boolean
    label: is Author
  - name: description
    type: textarea
    label: Description
  - name: image
    type: text
    label: Image
  - name: accolades
    type: field_group_list
    label: Accolades
    fields:
      - type: text
        label: Figure
        name: figure
      - type: text
        label: Description
        name: description
