import { successText } from "../../utils/theme";
import { print } from "graphql";

import fs from "fs";
import { queryBuilder } from "@forestryio/graphql-helpers";

export async function genQueries({ schema }: any, next: () => void) {
  const query = queryBuilder(schema);
  const queriesPath = process.cwd() + "/.forestry/query.js";

  await fs.writeFileSync(
    process.cwd() + "/.forestry/query.gql",
    `# DO NOT MODIFY THIS FILE. This file is automatically generated by Forestry
${print(query)}
`
  );

  console.log("Generated queries at " + successText(` ${queriesPath}`));

  next();
}
