import { successText } from "../../utils/theme";
import { generateTypes } from "../../codegen";
import { print } from "graphql";

import {
  buildSchema as buildForestrySchema,
  FileSystemManager,
} from "@forestryio/graphql";
import fs from "fs";
import { queryBuilder } from "../../codegen/queryBuilder";

export async function genQueries({ schema }: any, next: () => void) {
  const query = queryBuilder(schema);
  const queriesPath = process.cwd() + "/.forestry/query.ts";

  await fs.writeFileSync(
    process.cwd() + "/.forestry/query.ts",
    `// DO NOT MODIFY THIS FILE. This file is automatically generated by Forestry
export default \`${print(query)}\`
`
  );

  console.log("Generated queries at " + successText(` ${queriesPath}`));

  next();
}
