import { successText } from "../../utils/theme";
import { generateTypes } from "../../codegen";
import fs from "fs";

export async function genTypes({ schema }: any, next: () => void, options) {
  if (!options.typescript) {
    next();
    return;
  }

  const typescriptTypes = await generateTypes(schema);
  const typesPath = process.cwd() + "/.forestry/types.ts";

  await fs.writeFileSync(
    typesPath,
    `// DO NOT MODIFY THIS FILE. This file is automatically generated by Forestry
${typescriptTypes}
`
  );
  console.log("Generated types at" + successText(` ${typesPath}`));

  next();
}
