# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: yarn --version
      - name: Echo ident
        run: echo $FORESTRYIO_NPM_AUTH_IDENT
      - name: Echo token
        run: echo $FORESTRYIO_NPM_AUTH_TOKEN
      # - name: Install
      #   run: yarn install
      - name: Build
        run: yarn run ci:check:auth
  # npm-publish:
  #   name: npm-publish
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@master
  #     - name: Set up Node.js
  #       uses: actions/setup-node@master
  #       with:
  #         node-version: 10.0.0
  #     - name: Publish if version has been updated
  #       uses: pascalgn/npm-publish-action@06e0830ea83eea10ed4a62654eeaedafb8bf50fc
  #       with: # All of theses inputs are optional
  #         tag_name: "v%s"
  #         tag_message: "v%s"
  #         commit_pattern: "^Release (\\S+)"
  #         workspace: "."
  #       env: # More info about the environment variables in the README
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this as is, it's automatically generated
  #         NPM_AUTH_TOKEN: ${{ secrets.FORESTRYIO_NPM_AUTH_TOKEN }} # You need to set this in your repo settings
